### ISSUE TITLE
Missing dependency : setuptools

### ISSUE THREAD

**Issue by InfiniteProductions** [rndusr/stig#1]
I've tried to run stig on a RaspBerry Pi 3 with Raspbian and these packages are at least needed

`python3-urwid python3-aiohttp python3-blinker python3-appdirs python3-setuptools`

**setuptools** is not listed in the requirements.

**Comment by rndusr** [comment]
Somehow I thought setuptools was part of the python3 standard
library. Apparently it's not.

It's now mentioned in the README.
