### ISSUE TITLE
Package won't build from AUR

### ISSUE THREAD

**Issue by peaveyman** [rndusr/stig#101]
I am getting an error:
 pkgbase should not be an array 
When trying to build the package.

**Comment by rndusr** [comment]
No idea what that means. (I'm not an Arch user.)

@kazuoteramoto Can you help?

**Comment by peaveyman** [comment]
Yeah, it didn't dawn on my that you weren't the one who put the pkgbuild on AUR. Sorry about. I will leave a comment on AUR.

**Comment by rndusr** [comment]
It's ok. I probably messed something up when I pushed a bunch of big changes
today. (That tab completion is going to be *sweeeet* when it's fully done!)

**Comment by rndusr** [comment]
> Still getting used to how to rename a torrent and all that.

Please feel free to make suggestions. I'm just making things up as I go, and I
appreciate input from users who might have better ideas than I do.

**Comment by peaveyman** [comment]
When will the tab completion be done?

**Comment by rndusr** [comment]
The basics are pretty much done and all commands and their options (arguments
that start with "-") should all work.

Now I have to tell the individual commands how to get completion candidates.

Then there's additional information I'd like to display along with the
candidates, e.g. short forms ("mv" for "move" or "-s" for "--sort") and a short
explanation of what a command/option/filter/etc does.

Eventually you should be able to complete almost everything and quickly see what
that thing you're completing means.

I'll also add a few options that make the completion system more
configurable. And I'd like the gathering of the candidates to be asynchronous so
you don't experience a delay when typing while it's looking for all the possible
torrent names or things like that.

It's hard to tell. I'm guessing a few weeks, but it's probably going to be
months until I'm really completely satisfied. There's always something to
revise.

**Comment by peaveyman** [comment]
Thanks!!!

**Comment by kazuoteramoto** [comment]
@peaveyman Did you use any aur helper? I don't have any problem with building it with `makepkg`. In any case I pushed a change to remove the `pkgbase` and making `pkgname` not a array (we not building split packages). Can you try it?
