### ISSUE TITLE
Any chance of releasing useful widgets as a separate library?

### ISSUE THREAD

**Issue by tonycpsu** [rndusr/stig#107]
Hi, I would like to make use of the `Scrollable` widget, and perhaps some other nice things you've developed as part of this app.  I am aware that there has been [some discussion](https://github.com/rndusr/stig/issues/53) previously of integrating this functionality into urwid itself, but that doesn't seem to be in the cards given that there's a single maintainer who hasn't been very responsive lately.

With this in mind, I was wondering if you might consider releasing (or allowing someone else to release) some of bits of `stig.tui` as a library module.  This isn't as convenient for would-be developers as having them in urwid proper, but it would work around the problem, and prevent people from just copying the Scrollable code into their projects, which a simple search of Github suggests has occurred more than a few times.

Is this something you might consider?

**Comment by rndusr** [comment]
Yes, sure.

There is already such a package: https://pypi.org/project/urwid_satext/
I don't know if it's still maintained or if the maintainer would be interested
in my stuff.

If that doesn't work out, feel free to make a new package.

I'd put it on my todo list, but it's already so long I'll never get to the end.

**Comment by tonycpsu** [comment]
> There is already such a package: https://pypi.org/project/urwid_satext/

Neat. I had seen urwid-satext pop up in a couple of applications years back, but unaware that it was still actively developed.  (The [hg repo](https://repos.goffi.org/urwid-satext/) seems to have been updated 6 weeks ago.)

I actually maintain [my own project](https://github.com/tonycpsu/panwid) with a small set of widgets that I use in my apps.  It's also in PyPi.  Perhaps over time the satext author and I could pool our resources and bring in the stuff from stig to form a larger community-driven project.  The fact that he self-hosts outside of Github and uses Hg instead of git could make collaboration a bit more difficult, though -- for all its warts, Github is still the best place to put something to gain wider community adoption, so I feel like anything targeted at making things easier for new users should at least be mirrored here.

How about this -- since you've given your blessing to use the code, I'll start by integrating Scrollable into panwid.  I'll add you on as a co-maintainer (if you care to) and over time work with the urwid developers to get it integrated there.  (I sent emails to both Andrew Dunai and Ian Ward in the last week trying to find out what the state of the project is.)

Does that sound like a good plan?

**Comment by rndusr** [comment]
Firstly, thank you for your efforts.

This is completely your choice and I'll support you either way, but why not
contact the urwid-satext maintainer to see if they're interested in our classes?
Less urwid extensions is better and urwid-satext is already bigger than our
contributions combined. It doesn't really matter if your ultimate goal is
integration into urwid, but I'm not holding my breath.

I've actually been pondering forking urwid for a long time to remove Python 2
support and put some work into it, but I don't fully understand important parts
of it (e.g. ListBox.render() is a beast), so I wouldn't be very comfortable with
maintaining it. I also think that this would be a job for someone who knows how
to build a community, and I'm definitely not that guy. But if you're ever going
down that route, make sure to let me know.

BTW, I see you already have a scrollbar implementation in panwid. Why are you
interested in my implementation?

**Comment by tonycpsu** [comment]
> This is completely your choice and I'll support you either way, but why not contact the urwid-satext maintainer to see if they're interested in our classes? Less urwid extensions is better and urwid-satext is already bigger than our contributions combined.

Bigger how?  There's the size of the codebase, and then there's the size of the audience who might be reached by a successful community-driven project.  I've been doing urwid-adjacent development for years now, including some contributions to urwid proper, was just barely aware of urwid-satext when you mentioned it.  That's not because it's bad -- it looks quite nice, actually!  But it wasn't nearly as nice when I first became aware of it, so I sort of filed it under "things to maybe look into again some day."  And then I never saw it in my travels on Github, so it sort of fell off my radar entirely.

As I said above, I think a lot of this boils down to the fact that, for good or for ill, it's just really hard to be a visible project in this space if your project isn't hosted on Github.  I also think a Mercurial repository is going to be a limiting factor for other developers.  I learned Mercurial before I learned git, but I know a lot of folks don't know Mercurial, and aren't going to want to deal with learning another VCS for one small project.  And let's suppose they do clone from the maintainer's personal Hg server and make some changes, what do they do after that, email patches to the maintainer?  Ask for push permissions to his self-hosted repository?  I'm an old school guy at heart, but if the bar for contributions is higher, there will be fewer contributions.

> It doesn't really matter if your ultimate goal is integration into urwid, but I'm not holding my breath.

> I've actually been pondering forking urwid for a long time to remove Python 2 support and put some work into it, but I don't fully understand important parts of it (e.g. ListBox.render() is a beast), so I wouldn't be very comfortable with maintaining it.  I also think that this would be a job for someone who knows how to build a community, and I'm definitely not that guy. But if you're ever going down that route, make sure to let me know.

Well, I've done what I can to reach out to the current and former maintainers.  If I don't hear something from either of them in the coming weeks, perhaps a fork wouldn't be a bad idea, and I do think I could handle a lot of the community building aspects.

> BTW, I see you already have a scrollbar implementation in panwid. Why are you interested in my implementation?

What I'm interested in is `Scrollable` more than `Scrollbar`, because it can be used to scroll any widget, not just a `ListBox`.  My use case is that I want to scroll some long `Text` content and don't want to deal with carving it up into lines (the lengths of which need would vary depending on screen width) to be loaded into a `ListBox`.  So much easier just to wrap the `Text` with `Scrollable` and call it day.,

Aside from that, your `ScrollBar` does have the nice property of being a decoration widget that can be used with any `Scrollable` widget, while mine only works as part of the `ScrollingListBox` widget (which is also used by the `DataTable` widget.)  The advantages mine has are the ability to to pagination / "infinite" scrolling and to have the scrollbar show info about how much data remains to be loaded, when you're at the end, etc.

So, I think what I'd do if I were to integrate those bits into `panwid` would be to rewrite `DataTable` to use a standard ListBox plus your `Scrollable` and `ScrollBar` classes, and ditch my `ScrollingListBox`.  Then I'd tweak `ScrollBar` to add the bits that mine does that yours doesn't, mostly those pertaining to pagination.

**Comment by rndusr** [comment]
Well, satext has 16 classes and panwid has currently 2. But yeah, you'll get
more users and contributors on GitHub.

I'm looking forward to see how this works out and what you'll do with my Scroll*
classes.

I will close this issue now since it's not really related to stig. Further
discussion should go to the original urwid issue or maybe a new one.

https://github.com/urwid/urwid/issues/226

**Comment by tonycpsu** [comment]
> I also think that this would be a job for someone who knows how to build a community, and I'm definitely not that guy. But if you're ever going down that route, make sure to let me know.

Letting you know...

![image](https://user-images.githubusercontent.com/914142/55358589-c3051680-549d-11e9-932a-c5d6f9ce10d4.png)

**Comment by rndusr** [comment]
Thanks. What's your answer to Ian's question?

**Comment by tonycpsu** [comment]
Well, I'll nominate myself, of course.  You want in?

**Comment by rndusr** [comment]
Even if I felt more confident, I don't really have the time to really work on
urwid.  stig is already taking so much of my attention that I don't get to work
on my smaller side projects.

But I can think of at least one PR I'd make if there was a higher chance that
it'd get some attention.

Thanks a lot for taking this step.  Hopefully, others will start contributing if
there's more activity.

**Comment by tonycpsu** [comment]
Yeah, that's fine.  I've got the time to take a new project on, at least as of now.  As for activity, well, there's only one direction it can go, and my 24-bit color PR should at least make that contribution graph spike temporarily, so at least there's that.
