### ISSUE TITLE
Login and ssl support

### ISSUE THREAD

**Issue by Kirogo** [rndusr/stig#11]
Hi,
I've been looking for a replacement to transmission-remote-cli, and stig looks promising enough, but I still need ssl and login support for it to fit my needs.
I'm ready to contribute to the project to bring these features, but I'd need few pointers on where to start looking.

Cheers,
Alexandre.

**Comment by rndusr** [comment]
Login should already work. Use <USERNAME>:<PASSWORD>@<HOST> for the srv.url
setting.

I don't have any experience with SSL, but it looks like aiohttp supports it:
https://aiohttp.readthedocs.io/en/stable/client.html#ssl-control-for-tcp-sockets

The relevant code in stig should go into the connect() method of the
TransmissionRPC class in stig/client/aiotransmission/rpc.py. Looks like you
need to add a 'connector' argument to the session_args passed to
ClientSession.

I think I would add a property to TransmissionRPC that holds None or a path to
the certificate file, which can then be used with aiohttp.

Then add a new string setting in stig/settings/defaults.py and a hook in
stig/hooks.py that changes the new TransmissionRPC property whenever the
setting changes.

Welcome to stig, and feel free to keep asking questions.

**Comment by Kirogo** [comment]
Hi,
I've been looking a bit at the code, starting to get my head around this part of the code. Still have some time to understand everything fully, but I managed to connect with https to my transmission instance on my vps.

How I did it was to set the `srv.url` to `https://<username>:<password>@bt.domain.com:443`. My vps  has a virtual host listening on `bt.domain.com` which proxies everything to the port transmission is listening to. I didn't have to change anything on the code, which is great. I am gonna take a look to the TODO list and try adding something when I can find the time for.

This leads me to the question : how do you run the project on a dev setup (without installing everything before) ? Sounds like just running the main file doesn't work, and I'm a bit new on how to dev with a project already being configured with a setup.py file.

Cheers,
Alexandre

**Comment by rndusr** [comment]
> set the `srv.url` to `https://<username>:<password>@bt.domain.com:443`

Interesting! Sounds like aiohttp uses SSL automatically. Very nice.

> run the project on a dev setup (without installing everything before) ?

I use `pip3 install --user --edit path/to/stig`.

The '--user' switch installs everything under `~/.local` and `--edit` does not
really install it there but places some kind of pointer to `path/to/stig`.

You can also just run `python3 -c 'import stig; stig.run()'` in the main
directory.

I don't use `virtualenv`, but many people do and seem to love it, so maybe you
might want to check that out.

**Comment by Kirogo** [comment]
Virtualenv is rather for having your libs on a separate (local) folder rather then installed system-wide. 
What I like to do is having a `requirements.txt` file which list dependancies from which you install with a `pip install -r requirements.txt`. If you use a vurtualenv, you get everything installed locally, with no problem regarding versions, etc.
