### ISSUE TITLE
Failing test on Mac OS - `OverflowError: mktime argument out of range`

### ISSUE THREAD

**Issue by FlorianKempenich** [rndusr/stig#110]
Hey,

Upon cloning and running the project locally to explore it a bit more in depth, I realized one test was failing.
=> [`test_string__month_day_hour_minute_second` in `ttypes_test.py:L315`](test_string__month_day_hour_minute_second)

The test:
```python
    def test_string__month_day_hour_minute_second(self):
        with mock_time(1845, 5, 17, 3, 29, 4):
            ts = ttypes.Timestamp.from_string('08-07 09:28:07')
            self.assertEqual(int(ts), mktime('1845-08-07 09:28:07'))
        ... (second part passes) ...
```

The error:
```shell
OverflowError: mktime argument out of range
```

After a quick search on SO, it seems `time.mktime(...)` calls the underlying `mktime` function from the platform's C library - [source](https://stackoverflow.com/questions/2518706/python-mktime-overflow-error/2518828#2518828). I tested to run the tests on a Unix machine and everything works as expected, which tends to confirm that hypothesis.

The bug is definitely not critical since it seems it is a test-only artifact. Actual production code seems to work as expected, but still, I figured you might want to be aware of it.

I tried to fix it by replacing `time.mktime` with `calendar.timegm` and start from there, but then I ended up in Timezone hell. I am not used to dealing with local time in the domain, and definitely not in python. So I'll leave that one to you ;) Or if you can guide me a bit I can try again. Your call ;)

If you need me to run some more "experiments" under MacOS just let me know.

**Comment by rndusr** [comment]
The fix for this tests should be easy enough: Just increase the year 1845 until
it passes.

But this might be an actual bug. I don't think I'm catching OverflowErrors
anywhere. I'll have to see if I can reproduce this issue somehow with even
sillier dates.

**Comment by rndusr** [comment]
You were right and the OverflowError is thrown by this tests only because of the
year 1845. I just increased the year to 1945. Let me know if that fixes it for
you.

**Comment by FlorianKempenich** [comment]
Yep. That fixes it.
