### ISSUE TITLE
Color format descriptions are unclear

### ISSUE THREAD

**Issue by paulriddle** [rndusr/stig#113]
Default theme doesn't fit with what I have in my terminal. So I decided to create a custom theme. It is written

> Color names: default, black, white, dark gray, light gray, dark red,
light red, dark green, light green, dark blue, light blue, dark magenta,
light magenta, dark cyan, light cyan, brown, yellow

Are those the only colors available? There are supposed to be 256 of them and it appears that they all have names, according to [this cheatsheet](https://jonasjacek.github.io/colors/). I tried gold1 and it didn't work.

Then it says there is support for `#RGB` colors, but how to specify them? As far as I know RGB means something like

```
R: 255
G: 255
B: 215
```

Three decimal numbers. Usually `#` means hex colors like `#ffffd7` but it doesn't work either! Should I surround with `"`?

How to specify colors?

**Comment by rndusr** [comment]
"#RGB" means you specify a one-digit hex number per base color instead of the
usual two-digit format "#RRGGBB".

For example, "#f00" is the same as "#ff0000".

Do you have any suggestions on how to describe that more clearly?

**Comment by paulriddle** [comment]
Thanks. I checked, it works, double quotes must not be present, which kind of makes it look like a comment.

I think it's best to just give a few examples and mention that something like `#ff0000` won't work. Also worth noting that named colors might be affected by terminal settings. I use alacritty and have changed some colors in it's config. It affects stig by making `white` appear as black and `black` appear as white. However if I simply say `#fff` it will be white as expected.

**Comment by rndusr** [comment]
Thanks, I'll try to improve the default theme header.

The 256-color spectrum is hardcoded, so "#0f0" is always green, but the 16
colors are just *any* 16 colors.

The fact that color 0 is black, 1 is red, 2 is green and so on is just a
convention that most terminal emulators let you configure freely, so you can set
color 0 to white and color 7 (usually white) to black and you get your white
background terminal.  But that breaks the convention and stig (actually urwid,
the TUI library stig uses) displays black when you specify "white" and vice
versa.
