### ISSUE TITLE
Remove torrent and data

### ISSUE THREAD

**Issue by lepis0** [rndusr/stig#116]
Can I somehow remove torrent with data?
If I use `stig rm` -command it leaves torrents data to disk.

**Comment by rndusr** [comment]
$ stig -h rm
[...]
  --delete-files, -d  Delete any downloaded files
[...]

**Comment by rndusr** [comment]
There's also the default keybinding <t> <D> in the TUI which deletes the torrent
and all its files. <t> <d> deletes only the torrent.
