### ISSUE TITLE
More than one filter in tab

### ISSUE THREAD

**Issue by Erebea** [rndusr/stig#119]
Is this even possible? I keep trying to exclude two different paths and it isn't working, am I doing it wrong?

`tab ls !path~dir1 !path~dir2 --columns name,peers,rate-down,rate-up,eta,downloaded,uploaded,size,ratio --sort added`

**Comment by rndusr** [comment]
From `stig help filtersmanual`:

  Filters can be combined with the operators "&" (logical AND) and "|" (logical OR).  Multiple
  FILTER arguments are implicitly combined with "|".
  Example: "name=foo paused" is the same as "name=foo|paused".

So this should work: ls '!path~dir1 & !path~dir2'
