### ISSUE TITLE
Add proxy server feature

### ISSUE THREAD

**Issue by mikeboiko** [rndusr/stig#121]
I would love to be able to connect to my bt server through a SOCKS proxy.
Would it be possible to add proxy support to stig please?

**Comment by apexo** [comment]
aiohttp w/ aiohttp_socks actually supports SOCKS proxies: [https://pypi.org/project/aiohttp-socks/](https://pypi.org/project/aiohttp-socks/)

**Comment by apexo** [comment]
So, let's imagine you have transmission running somewhere as a tor hidden service (on port 9091), and a tor daemon running locally, you could now connect there via:

```
set connect.url http://user:password@xyzxyzxyz.onion/transmission/rpc
set connect.proxy socks5://127.0.0.1:9050
```

**Comment by mikeboiko** [comment]
@apexo, thanks for the info. I will check that out.
@rndusr, feel free to close this issue. There are definitely other ways I can solve my problem without you having to integrate a SOCKS proxy into stig.

**Comment by rndusr** [comment]
@mikeboiko, @apexo was nice and implemented it.

https://github.com/rndusr/stig/pull/169

**Comment by mikeboiko** [comment]
Thanks @apexo, I'll be looking out for this feature!

**Comment by rndusr** [comment]
Setting "connect.proxy" should be working now.

**Comment by mikeboiko** [comment]
Awesome, thank you guys!
