### ISSUE TITLE
Torrents not highlighted when using tmux

### ISSUE THREAD

**Issue by Steap** [rndusr/stig#125]
When running stig inside a terminal I get the following screen:

![stig-outside-of-tmux](https://user-images.githubusercontent.com/416834/71770144-bbd9d000-2f29-11ea-9963-bf12163318ba.png)

When running stig inside a tmux session, I get the following screen:

![stig-inside-of-tmux](https://user-images.githubusercontent.com/416834/71770924-8cc85c00-2f33-11ea-920e-cb363965f483.png)

The currently selected torrent is not highlighted (its background color is not the usual gray), but I can still navigate "blindly" through the list using 'j' and 'k'.

This was tested with both stig 0.10.1a0 (from PyPI) and the master branch (49b864f9a1ab98179c9e216c20093988991b1ac2).

The behaviour is correct when using GNU screen.

**Comment by rndusr** [comment]
I think the best fix would be to make a theme for tmux.

I'm planning on switching to a different TUI library, so I'm not going to
investigate this.

**Comment by Steap** [comment]
Let's close this bug then :)
