### ISSUE TITLE
Add sort option for age / date added

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#130]
I didn't see a sort option for how long the torrent has been in the client. I like to sort in other clients by date added with the newer stuff at the top so I can easily see what's currently downloading or has recently finished.

**Comment by rndusr** [comment]
You can do this (":sort added"), there is just no default keybinding for it.
There are too many sort orders, it would make the list too long. Check out
":help sort".

**Comment by Soundtoxin** [comment]
Thank you. I will look harder next time.

**Comment by Soundtoxin** [comment]
Is there a way to save the sort order? I like `:sort !added` and after a server power failure I had to look through my old commands to find out how I sorted it this way before.

**Comment by rndusr** [comment]
Strictly speaking, stig doesn't have a concept of configuration, but it runs
commands from a file at startup. I call them "rc files".

"stig help cfgman" should get you started on rc files. (You could've discovered
this command via "stig -h".)

You can set default sort orders with the "sort.*" settings ("stig help sort.torrents").

If you don't open any tabs in an rc file, stig opens some default tabs for you.
If you want specific default sort orders in specific tabs, put something like
this in ~/.config/stig/rc:

    tab ls active --sort status,path,eta
    tab ls stopped --sort foo
    tab ls path~/bar/ --sort ...

**Comment by Soundtoxin** [comment]
First of all, thank you so much for the help, and second, this program is really amazing the more I learn about it! Great work!

I had also been wondering if I could specify my host and port somewhere so that I could just run "stig" instead of the longer/more specific thing, and now that I know about the rc file, I just tried adding it in at the same time as the sort option and it worked on the first try!
I probably should've looked at the help pages some more to find this out, I guess it didn't occur to me.

**Comment by rndusr** [comment]
Thanks for the praise. :)

The more documentation you read, the better the software becomes.
