### ISSUE TITLE
Adding torrents by non-magnet URL

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#131]
I'm not clear if I'm doing this wrong or if it's a missing feature, but I often add torrents by copying their url (from the DL button) to my clipboard from a browser and then pasting them into a torrent client. It works for most sites I use. Works in `transmission-remote-gtk` as well, but doesn't work with stig. I tried `:add urlhere` and I tried with and without quoting the url. It assumes that it's a local file, like it says it can't find it at `/home/user/URL`.

**Comment by rndusr** [comment]
You're not doing anything wrong. It's a bug.

**Comment by rndusr** [comment]
Should be fixed in current master.

**Comment by Soundtoxin** [comment]
Works great! Thanks so much. I had been using transmission-remote-gtk just to add things and then switching to stig to move them and such. I should be able to use stig for everything now.
