### ISSUE TITLE
Can't rename two torrents/torrent directories to the same thing

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#132]
Basically imagine you're downloading a TV show in parts, BluRay volumes, so you get a couple episodes each, but you want all the episodes in the same directory, not a bunch of fragmented ones. So you rename from "TV Show Volume 4" and "TV Show Volume 5" (two different torrents) to just "TV Show" for each of them, a directory you already have from downloading the older volumes, then you set the download location to one dir higher (such as `/storage/tv`) and all the episodes can end up in the same place because the two "TV Show" directories will merge, putting the episodes from both volumes in the same place. This works fine in `deluge-console`, but with stig I get this error `23:12:41 x2 rename: Torrent already exists in /storage/tv: TV Show`.
i would really like it if this could be fixed!

**Comment by rndusr** [comment]
IIRC, the issue was that Transmission overwrites the destination. Can you do
this with other Transmission frontends?

A workaround is to move the torrent somewhere else, rename it and move it back.

**Comment by Soundtoxin** [comment]
> Can you do this with other Transmission frontends?

I would love to test, but a big reason I came to stig is because I was struggling to find other frontends that let me rename files at all! If I can get access to `tremc` or `transmission-qt` (neither of which are packaged on my main distro) I will test.

**Comment by Soundtoxin** [comment]
> A workaround is to move the torrent somewhere else, rename it and move it back.

I just confirmed this workaround works, so thanks for that. I renamed the second thing to the same as the first before moving it, when the first was already renamed *and* moved. I still haven't gotten around to testing other clients, but I'll keep you updated on that.

**Comment by rndusr** [comment]
Thanks for the confirmation.

**Comment by rndusr** [comment]
After some testing, I disabled the safety check and renaming torrents to an existing path
should now work.
