### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by ju1m** [rndusr/stig#133]
While I'm at polishing the stig package in Nixpkgs, I've seen that it packages the 0.10.1a release which dates back to 2018. Would it make sense to package a more recent version? And if so, could you make a new release to guide me? Thanks!

**Comment by rndusr** [comment]
Yes, I'm hoping to make new release soon. The major blocker is that tab-
completion is not implemented for all commands.

Thanks for packaging. Let me know if I can make your job easier.

**Comment by ju1m** [comment]
Great :) Take your time. When you'll judge it's release-time, just making a release tag like before and closing this issue to notify me should be enough as far as I'm concerned. Thanks for coding stig!

**Comment by rndusr** [comment]
New release is out. :)
