### ISSUE TITLE
Sorting tabs

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#134]
Hi,

I'd like more control over the order of the tabs. I'd be fine with a manual way to move the currently focused tab, e.g. <kbd>H</kbd> moves it to the left, or <kbd>alt-\<number></kbd> moves it to slot #`number`.

Unless that's already possible?

Thanks!

**Comment by rndusr** [comment]
No, it's not possible at the moment, but I've missed that feature myself.

Unfortunately, I'm planning on rewriting the TUI code, so any work on the
current implementation is going to be wasted.

But there will be one last release with the old TUI code. Maybe adding movable
tabs is not too much work.

**Comment by lenormf** [comment]
Right, just close this issue if you get around to doing it. I'll wait otherwise!

**Comment by rndusr** [comment]
OK, it was pretty easy. You can now move tabs with shift-h and shift-l.
