### ISSUE TITLE
Bad config example in README

### ISSUE THREAD

**Issue by simonbcn** [rndusr/stig#14]
```
Arch Linux
stig-git (installed from AUR package today)
```

In [README](https://github.com/rndusr/stig/blob/master/README.org#example-config) there is the next config example: `set tlist.columns name ratio rate-up rate-down` but it fails to me: `Unknown setting: tlist.columns`

How can I define the default columns (_and sort_) to show in TUI?

**Comment by rndusr** [comment]
The new name of that setting is "columns.torrents".

stig-git follows the development version, which is in the dev branch. master is
the current stable release. Check out dev to get the correct README.

Or you can run `stig help settings` to get a list of all settings.

**Comment by simonbcn** [comment]
ok, I thought that _master_ was development.
