### ISSUE TITLE
Information about disk-space left

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#146]
Hi,

With `transmission-remote-cli`, I can see how much disk-space is available when adding a torrent with <kbd>a</kbd>.

Is this information available anywhere in `stig`? Could it be made available, for example in a tab populated by e.g. a `systeminfo` command?

Thanks!

**Comment by rndusr** [comment]
No, it's currently not possible.

I'm planning to add some kind of "exec" command that lets you run arbitrary
shell commands (mpv, mediainfo, etc). That could be used to run "watch du -h
..." or something similar.

I don't think it's a good idea to add a "systeminfo" command. That's not really
stig's job. Maybe something really simple if the "exec" solution isn't enough.
We'll see.

None of that is going to be in the next version, though.

**Comment by lenormf** [comment]
The point is to know whether the target download directory (either the default one, or the one passed to `add -p`) has enough space to download the given torrent. I don't care much for the custom command, that was just what I could think of, off the top of my head.

I had a look at the code, how about a widget for the bottom bar that shows the disk space available in `srv.path.incomplete`/`srv.path.complete`, next to the torrent counters? It could also be just one number if both paths are identical.

**Comment by rndusr** [comment]
That sounds reasonable and shouldn't be too complicated.

If you want to submit a PR, I can include it in the next release. Keep in mind
that the daemon might run on a different machine. I suggest to not display
anything in that case.

I've been thinking about adding a configurable ssh command that could fetch
information like than and also for tab completion system, but that's probably
not trivial.

**Comment by lenormf** [comment]
Hi,

I have a working implementation which I'm polishing for a PR. I just wanted to ask you how I could space two widgets apart with a single space? I tried the following, but it's not working(

```python
bottombar.add(name='counters', widget=TorrentCountersWidget(), options='pack')
bottombar.add(name='_spacer1', widget=urwid.AttrMap(urwid.Text(' '), 'bottombar'))
bottombar.add(name='diskspace', widget=AvailableDiskSpaceWidget(), options='pack')
```

**Comment by rndusr** [comment]
Maybe add `options='pack'` to the spacer?

If you can't figure it out, just make the PR with the bad spacing and can fix it. It's
always easier to fix bugs you can touch.

**Comment by lenormf** [comment]
That did it! PR updated.
