### ISSUE TITLE
How can I see details of torrent?

### ISSUE THREAD

**Issue by simonbcn** [rndusr/stig#15]
I'm testing the dev version of stig on Arch Linux.
How can I see details of torrent like Privacy, Error?

**Comment by rndusr** [comment]
That is not implemented yet.

Can you make a list of what you are interested in mostly?

**Comment by simonbcn** [comment]
Principally the completed date and error (_if any_). Thanks.

**Comment by simonbcn** [comment]
I meant to see all the details of torrent as can be seen in Transmission. If I press `ENTER` on a torrent I can see the file list but nothing else.

**Comment by rndusr** [comment]
I'm not familiar with the Transmission GUI. Can you make a screenshot?

**Comment by simonbcn** [comment]
![captura de pantalla de 2017-04-05 16-51-56](https://cloud.githubusercontent.com/assets/428231/24711437/4234735c-1a20-11e7-8593-0fbfe7e8b448.png)
