### ISSUE TITLE
Can't install development version with pipx

### ISSUE THREAD

**Issue by kahn10** [rndusr/stig#153]
Running the command:
pipx install 'git+https://github.com/rndusr/stig.git#egg=stig'

returns:
Package cannot be a url

**Comment by kahn10** [comment]
I was able to install with pip3. I'm assuming this is some setting with pipx on my own computer.

**Comment by rndusr** [comment]
Nope, there's something with that pipx command.

Thanks for the report.

**Comment by rndusr** [comment]
Actually, you're probably using an older pipx version. Try this:

    pipx install stig --spec 'git+https://github.com/rndusr/stig.git#egg=stig'

**Comment by kahn10** [comment]
That installed a version (0.10.1a0) but it doesn't have the hash feature.

**Comment by rndusr** [comment]
What does `pipx --version` say?

**Comment by kahn10** [comment]
0.12.0.4
I tried to update it with apt, but it was the most recent available on my system. I'm sure I could have tried to update my pipx another way, but I was able to get stig 0.11.0a with pip3, so I didn't pursue it.

**Comment by rndusr** [comment]
I guess it's the older version. The above command works for me with pipx 0.12.3.1.

You could install the latest pipx with pip3. But since you've installed stig with pip3
there's not really a point because your ~/.local is already in a state of eternal mess. :)

**Comment by rndusr** [comment]
I assume this is no longer an issue.
