### ISSUE TITLE
a dark theme+ minor theme issue

### ISSUE THREAD

**Issue by BachoSeven** [rndusr/stig#155]
Hi, just wanted to share this theme if anybody wants a dark theme which looks (imo) pretty light on the eyes. It is tested with both Grubox and Solarized Dark colors on my `st` terminal emulator, so it could look slightly different with other colorschemes. I attach the colorscheme and a couple of screenshots.

btw, I sometimes experience this error `set: tui.theme = theme.theme: Invalid line #43: '$name_fg \t       = light blue'` when increasing the indenting in my colors definitions from, for example
```
$name_fg = light blue
```
to
```
$name_fg 	       = light blue;
```
even though I have plenty of indented definitions. 

EDIT: okay the issue is using tabs, for some reason. Also I forgot to attach: 

[Theme](https://pastebin.com/vTDJCrBQ)
[Screens](https://imgur.com/gallery/q8k143J)

**Comment by rndusr** [comment]
Nasty tabses! Should be fixed now.

And thanks for sharing your theme! Looks nice.
You're actually the first one, so congrats!
