### ISSUE TITLE
Feature Request: show torrent contents in a tab

### ISSUE THREAD

**Issue by BachoSeven** [rndusr/stig#159]
This is probably related to #126; however I was thinking more of a tab which just lists the contents (filename, type, size, and perhaps even downloaded percentage). Not sure if it can be implemented, just throwing it out there.

**Comment by rndusr** [comment]
The filelist/lsf command lists all of that except file type. Did you miss that?

**Comment by BachoSeven** [comment]
I did indeed :'D. Thanks for pointing it out!
