### ISSUE TITLE
Any way to buy you a coffee?

### ISSUE THREAD

**Issue by adworacz** [rndusr/stig#168]
I’ve been very impressed with stig, coming from rtorrent’s tui. 

The emphasis on vim key bindings, plus the emacs style command menu, easy install using pipx, and the list goes on. 

I’d love a way to support your work, similar to a ‘buy me a coffee’ badge. 

Any interest in adding something like that to your README?

**Comment by rndusr** [comment]
Wow, thank you. That's very nice of you.

Unfortunately, I don't know of any way to receive money easily, anonymously and without
wasting a lot of energy.

Also, if people were actually donating, I'd feel like I owe them. I'm not going to work on
stig for the the next few months, so opening donations now would be kind of a dick move.

But if you have too much money, you could use Bountysource or something similar to get
this bug fixed: https://github.com/urwid/urwid/issues/90

**Comment by adworacz** [comment]
Okay will do, thank you for your response. I’ll look into that bug you pointed to.
