### ISSUE TITLE
[Enhancement] Possibility of named tabs

### ISSUE THREAD

**Issue by simonbcn** [rndusr/stig#17]
It would be nice to can assign names to tabs.
For example:
```
tab "stopped&to-be-deleted" ls stopped&path~borrar --sort !ratio --columns name,size,ratio
tab "Descargados" ls path~borrar --sort !ratio --columns name,size,ratio
```
The text between quotes would be the tab title.

**Comment by rndusr** [comment]
Your proposal doesn't work because there is no way to tell if the first argument
is part of the command or a title.

I've added an option instead: --title or -t
