### ISSUE TITLE
Auto invoke and auto kill transmission-daemon

### ISSUE THREAD

**Issue by timsofteng** [rndusr/stig#183]
Hello. Can stig automatically open and close transmission-daemon by itself?

**Comment by rndusr** [comment]
No.

I think the API provides a command to shutdown the daemon, but I don't think
starting it is doable. stig doesn't know how it was started. Was it started by
PID 1? Is your PID 1 systemd? Or maybe you started it manually in a terminal in
the foreground for testing purposes? Is the daemon running on remote computer?
If that computer allows you to execute commands, by what means? SSH? Some
proprietary web interface?
