### ISSUE TITLE
Adding trackers on the fly

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#187]
Hi,

I haven't checked it Transmission allows this in the first place, but it'd be nice to be able to add trackers to an existing torrent, from the trackerlist tab.

Thanks!

**Comment by rndusr** [comment]
Why haven't you checked?

I mean, it's ok if you can't find anything because the documentation sucks, but
why do you request a feature before even trying to find out if it already
exists?

**Comment by lenormf** [comment]
I checked the on-board bindings documentation page, I meant that I don't know if it would be implementable in Stig, potentially because Transmission doesn't allow it.

That's your job to check ;)

**Comment by rndusr** [comment]
Oh, there was a typo. You wrote "I haven't checked it Transmission allows this
in the first place". I thought you forgot a comma after "it", but it should be
"if", of course, which makes much more sense.

Anyway, it'a already implemented.

    $ stig help
    [...]
        commands, cmds                    - Lists commands
    [...]
    $ stig help commands
    [...]
      tracker, trk               Add/Remove trackers to/from torrents
    [...]
