### ISSUE TITLE
"RuntimeError: Event loop stopped before Future completed." when quitting

### ISSUE THREAD

**Issue by 0xC0ncord** [rndusr/stig#188]
v0.11.2a0 (python3.8) gives me this error every time I quit the application:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/stig", line 33, in <module>
    sys.exit(load_entry_point('stig==0.11.2a0', 'console_scripts', 'stig')())
  File "/usr/lib/python3.8/site-packages/stig/__init__.py", line 25, in run
    main.run()
  File "/usr/lib/python3.8/site-packages/stig/main.py", line 105, in run
    asyncio.get_event_loop().run_until_complete(srvapi.rpc.disconnect('Quit'))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 614, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```
This isn't really a big deal, but it's pretty noisy.

**Comment by rndusr** [comment]
I noticed that, too. I successfully fixed that bug by kicking it down the road
until Python 3.9 came out and it vanished into thin air.

I don't have to time to debug this unless it's more than annoying.

**Comment by 0xC0ncord** [comment]
> I successfully fixed that bug by kicking it down the road until Python 3.9 came out and it vanished into thin air.

Hah. I'm not really bothered by this bug so I don't mind closing it, but maybe it should stay open for visibility or until there's a proper fix?

**Comment by rndusr** [comment]
Yeah, sure.

**Comment by yookoala** [comment]
I am using Python 3.9.1 but I still see this error when quitting.
I installed stig with pip instead of pipx. Not sure if this is relevant.

**Comment by rndusr** [comment]
Weird. I can reproduce this with the pyenv Python but not with my system Python.

Anyway, it looks like the fix was pretty easy. Let's hope this doesn't blow up
anything else.

**Comment by yookoala** [comment]
Just checked out `stig-0.12.0a0` and confirm the issue is fixed.

**Comment by rndusr** [comment]
> Just checked out `stig-0.12.0a0` and confirm the issue is fixed.

Thanks.

**Comment by rndusr** [comment]
With my fix I'm getting an "Unclosed client session" when not using the TUI
(`stig ls foo`).

I think I've found a fix that solves both issues, but I'm having a hard time
reproducing the original issue reliably.

Can someone pull from master and confirm that `stig` and `stig ls foo` don't
produce any unexpected output?

**Comment by yookoala** [comment]
Just tried this:
```
$ git clone https://github.com/rndusr/stig.git
$ cd stig
$ python3 -m stig ls foo
list: No matching torrents: ~foo
$ python3 -m stig
```

When I quit by `q`, the message is still gone. Is that enough?

**Comment by rndusr** [comment]
Yes, looks great. Thank you.
