### ISSUE TITLE
Stuck when downloading from magnet link

### ISSUE THREAD

**Issue by BioBox** [rndusr/stig#194]
This thing is really great when it works, and it does that just fine when downloading a `.torrent` file, but when trying to download a magnet link it just gets stuck and doesn't download anything. However, when downloading with the transmission gui client it works. If you could provide me with an example magnet link so that I can try to debug/log it or something that would be greatn.

It shows "discovering" under status and when I look into the detailed page it says "Error: Connection failed." I have no idea what's causing it. I know it's not the link itself because it works with other transmission clients.

EDIT: It might not be downloading it correctly (I just copy and paste the link into the add command), but it shows the title correctly. I'm using Python 3.9.5 with transmission-cli 3.00 btw

**Comment by rndusr** [comment]
This downloads as expected:
magnet:?xt=urn:btih:eb6354d8d9b9427458af8bee90457101a4c1e8e3&dn=archlinux-2021.05.01-x86_64.iso

stig just hands the torrent or magnet link to transmission-daemon. If you get
"Error: Connection failed", transmission-daemon isn't responding to stig's
requests for status information.

**Comment by BioBox** [comment]
Okay that one works for me. Thank you for explaining what's actually going on. I tried adding it via the cli interface `transmission-remote` and the behavior was the same. I tried Some other magnets and they worked fine.

I don't why that specific one had issues, _but it definitely isn't the fault of stig_. Thank you for your help.
