### ISSUE TITLE
Seeding a A Torrent you Already have the Files for

### ISSUE THREAD

**Issue by BioBox** [rndusr/stig#199]
I created a new torrent using your `torf` utility and would like to add it to stig to start seeding **without leeching** however I'm not sure if stig has the functionality for that.

If not, then how would you do it in Transmission?
Thanks.

**Comment by rndusr** [comment]
$ stig -h
    $ stig -h commands
    $ stig -h add

Just add it with the correct path:

    $ stig add your.torrent --path /where/the/torrent/file/are

If the path is correct and the transmission-daemon user can read
/where/the/torrent/file/are, it will verify the files and start seeding.

You can also add the torrent without the path, move it and verify it.

**Comment by BioBox** [comment]
Ok my mistake was that I was pointing stig over to the directory of the torrent instead of the _directory **containing the torrent**_. Thanks. torf is awesome btw.
