### ISSUE TITLE
Missing building instructions

### ISSUE THREAD

**Issue by InfiniteProductions** [rndusr/stig#2]
Python is not my thing so I have to do a bit of guesswork and it would be great to have some guidance on how to build and run _stig_ without wasting too much time/effort doing all what you've already done on your side.

Any chance also to get some binary package for common distros ?

**Comment by rndusr** [comment]
stig is still in alpha stage. I'm planning on releasing beta soon and put it
on pypi. Then you will be able to install with `pip3 install stig`.

For now you have to clone it first and install from a local path.

```
git clone https://github.com/rndusr/stig && pip3 install ./stig
```

Concerning distro packages, you have to contact the package maintainers of
your distro. (Or become one yourself.)

**Comment by rndusr** [comment]
I've added a "Installation" section to the README
