### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lenormf** [rndusr/stig#202]
Hi,

It's been a while since a release has been made, could we have one please?

Thanks!

**Comment by rndusr** [comment]
Why? There's only one minor bugfix and a minor feature in the CHANGELOG.

**Comment by lenormf** [comment]
It's been a while, and since there's a bug fix it could be included in a minor release `v0.12.1`. This is mostly so I can point my configurations at a release number that is more or less recent, without having to use a development version after months of inactivity on the project.

**Comment by rndusr** [comment]
0.12.2a0 is out.

**Comment by lenormf** [comment]
Thanks!
