### ISSUE TITLE
Change Theme

### ISSUE THREAD

**Issue by glmsmoura** [rndusr/stig#204]
I liked stig a lot, but topbar's color are horrible in my term. I wish to know if there is any other theme, or if there is a simple way to create one, I tried to read theme.py, but I didn't understand it well.

**Comment by rndusr** [comment]
$ stig help tui.theme

This tells you the path of the default theme file. Copy it to
~/.config/stig/my.theme and edit it to your liking.

    $ stig set tui.theme my.theme

To always use it, add that command to your rc file.

    $ echo 'set tui.theme my.theme' >> ~/.config/stig/rc

**Comment by glmsmoura** [comment]
Thanks for the quick answer! 

It worked like a charm! But, if I want to change my color pallete, is there a way to do it? For example, in my term, light green and dark green are almost the same color.

**Comment by rndusr** [comment]
The color pallet is specified by your terminal.

If your terminal supports 24-bit colors, you can use #RGB color codes.
