### ISSUE TITLE
[Question] Is there any way to disable the top bar.

### ISSUE THREAD

**Issue by SmellsNice** [rndusr/stig#208]
As the title says I would like to disable the bar which shows transmission version and port. Right now the closest I know how is to use a theme to make it match my background colour but that leaves a noticeable gap.

**Comment by rndusr** [comment]
$ stig help
    [...]
    commands, cmds                    - Lists commands
    [...]
    $ stig help commands
    [...]
    tui                 Show or hide parts of the text user interface
    [...]
