### ISSUE TITLE
How to reset torrent settings so that it uses global settings?

### ISSUE THREAD

**Issue by tgharib** [rndusr/stig#219]
This feels like a dumb question but I seem to be overlooking something obvious.

I have 20 torrents or so and it seems that some of them have settings customized for their particular torrent. For example: my global upload limit is 1 MB/s but some torrents seem to have an upload limit of 5 MB/s while others have unlimited upload limit. How would I be able to reset a torrent so that it uses the global setting of 1 MB/s?

**Comment by rndusr** [comment]
Everything should be documented. Get started by running "stig help".

The command you're looking for is "ratelimit".

**Comment by tgharib** [comment]
Sorry, I suppose I wasn't clear.

My intention is not change the rate limit. The rate limit was just an example. Basically, I am asking: how would I be able to reset all per-torrent setttings for all torrents?

**Comment by rndusr** [comment]
OK, thanks for clarifying.

This is not possible and I'm not sure it would be a good idea because it's
unclear what a per-torrent setting is.

For example, the torrent's location is a per-torrent setting, but do I want to
move them all to the default download directory when I reset all per-torrent
settings? Possibly, but the user can't predict what it does and stig can't know
what the user means exactly.

**Comment by tgharib** [comment]
>For example, the torrent's location is a per-torrent setting, but do I want to
move them all to the default download directory when I reset all per-torrent
settings? Possibly, but the user can't predict what it does and stig can't know
what the user means exactly.

Makes sense. I had to resort to transmission-qt to see which settings are set per-torrent. I couldn't find a way to set seed ratio limit in stig either.

![screenshot](https://user-images.githubusercontent.com/6457015/164299278-0db560d0-ffab-4d0c-920e-883c550c7c17.png)

**Comment by tgharib** [comment]
> I couldn't find a way to set seed ratio limit in stig either.
> It's not implemented, and I don't know why that setting even exists. Why would you stop seeding after a certain ratio? If you need the disk space, you delete the torrent. If you need the bandwidth, you can limit it globally or per torrent.

On public trackers, seeding is like a firehose that is always running but can never extinguish the fire. I would rather stop seeding on torrents with high ratios so that torrents with low ratios can get upload bandwidth.

**Comment by rndusr** [comment]
I see.

I have a cronjob that runs this every day:

    stig ratelimit up   1Mb '!limit-rate-up & ratio>=3 & ratio<5'
    stig ratelimit up 512kb '!limit-rate-up & ratio>=5'

This doesn't kill torrents and people can still download them, it just takes forever.
