### ISSUE TITLE
Filter torrents by the Private flag in CLI

### ISSUE THREAD

**Issue by Czechball** [rndusr/stig#222]
Hello. Is there a way to filter torrents based on their Private flag? I'd like to do this in CLI since TUI doesn't run well on my machine, if possible. I'm aware that stig's codebase is currently in maintenance mode, so I'm mostly just asking if this is even possible in the first place or perhaps if there are any workarounds to do this.

**Comment by rndusr** [comment]
$ stig help filters | grep private
$ stig ls private
$ stig ls '!private'

**Comment by Czechball** [comment]
Thanks.
