### ISSUE TITLE
Can we have regex, please?

### ISSUE THREAD

**Issue by The-Sound** [rndusr/stig#229]
Hi! This is more a request than an issue.

I was trying to filter some torrents with the format `Name 101-200`

I thought that as we have `&` and `|` and using `~` for literal strings, I could use `*`, `?` or `.` to filter them, something like `Name ?01-?00` (my use of regex is bad at best, so don't mind that if that's not the issue, sorry) but I was wrong.

It would be too hard to add? Seems like a nice thing to have, thank you.

**Comment by rndusr** [comment]
Regular expressions are already implemented. This should work:

    $ stig ls '=~S\\d+' -c name

It's documented here:

    $ stig help filtersmanual

**Comment by The-Sound** [comment]
Sometimes I'm a little bit dense, but the bit that in theory covers regex would be this one?

```
  Besides the usual operators (=, !=, >, <, >=, <=), "~" matches if the item's value contains the
  literal string VALUE and "=~" matches if the item's value matches against the Perl-style regular
  expression VALUE.
  Example: "name~foo" matches all torrents with "foo" in their name.
```

Just asking because I've read a few times that `help` before opening another issue but maybe I missinterpreted it. Should I go to Perl docs in search of more examples then?

**Comment by rndusr** [comment]
I agree that there's room for improvement, but stig is not the place to document
regular expression syntax.

The exact implementation used by stig is documented here:
https://docs.python.org/3/library/re.html
