### ISSUE TITLE
Provide .desktop file 

### ISSUE THREAD

**Issue by Alterrien** [rndusr/stig#23]
Hello !
So, I've been thinking of adding a .desktop entry for stig, for linux systems. This would allow two things : 
This first would be to be able to launch stig from a desktop shortcut or a launcher, if your DE/WM gives you this.
The second (and most useful, IMO), would be to have hooks on magnet links and torrent files, so that, when downloading a torrent file, you can add it instantly via stig, instead of having to store it somewhere, and then lauch your terminal, and then do the "stig add...". This would also let you double-click on a .torrent file, if you have a file explorer, and it would add it automatically.
I can research it a bit more tomorrow, does this interest you ? The change would be to add a .desktop file to the project, and add a line to the setup.py file, to put the desktop entry under /usr/share/applications

**Comment by rndusr** [comment]
Sounds like a great idea.  I didn't know .desktop are used for associating files
with applications.

The only thing I wouldn't like is a hardcoded `/usr/share/applications` path.
If you provide `--user` to `pip3`, it installs everything under `~/.local/`
instead of `/usr/`, so installing the .desktop file system-wide would be very
messy.

I know .desktop files work if they are put in `~/.local/share/applications/`,
but I don't know how to configure setup.py correctly.

**Comment by Alterrien** [comment]
Alright, so I've been digging at it, and I managed to somehow get a working desktop file : 
```
[Desktop Entry]
Name=Stig
Comment=TUI and CLI for the BitTorrent client Transmission
Terminal=true
Exec=stig add %U
Type=Application
MimeType=application/x-bittorrent
Categories=Network;FileTransfer;P2P;
Keywords=p2p;bittorrent;transmission;rpc;
```
So this works when using `xdg-open` on a torrent file (so it'll work when clicking on the file in any file explorer), But you can't use it to launch stig, as it'll fail with no file given.

So, unless we can have a better option (I'm thinking the Actions on the desktop file, but I'm not sure of how it works), we might need several desktop files, which is suboptimal. What do you think of that ?

**Comment by rndusr** [comment]
I don't know much about desktop files (never used them), but I don't think two
desktop files for one application is a good idea. No idea what Actions are.

You could always write a helper script that assumes all arguments are torrent
files. If no arguments are provided, it opens a terminal with the TUI.

You could even use something like zenity to provide a dialog that allows some
options like "download path" and "don't start downloading".

**Comment by rndusr** [comment]
I think this should be part of some other project. A GUI dialog window that
displays torrent data and lets you pick a download directory before adding the
torrent.
