### ISSUE TITLE
[Question] Sluggish opening/closing of torrent details (:tab info)

### ISSUE THREAD

**Issue by ian-s-mcb** [rndusr/stig#236]
This question might be moot given the maintenance mode of this project, but I've seen a noticeable increase in sluggishness of stig over the last year on the same hardware. I always keep my OS up-to-date and I use Arch Linux and Sway.

It takes close to two seconds for stig to open or close the details for an existing torrent where transmission-daemon is running locally. Only 5-10 torrents have been added to transmission and none of them especially busy in terms of current traffic. Is this typical for stig these days? Thank you for creating stig and I hope one day you'll release its successor. 

Below is my version info. I use the stig-git AUR package, but I tested the PyPI package too and both have the issue on my hardware. I wish I could recall the release that introduced the sluggishness, but time and OS updates when by and I just put up with the issue until today.

```sh
$ pacman -Q stig-git
stig-git 0.12.4a0.r1.90613afd-1
$ stig --version
stig version 0.12.4a0
$ python -V
Python 3.11.3
$ uname -r
6.3.6-arch1-1
```

Here are the specs on my dated, but adequate, hardware:

```
Machine-1 - a desktop
CPU: Intel Core i5-8500, 6 cores, 6 threads @ 4.100GHz
RAM: G.SKILL Aegis 40 GB, DDR4 3000
Storage: HP EX950 NVMe, 512 GB

Machine-2 - a laptop
CPU: Intel Core i5-8250U, 4 cores, 8 threads @ 3.40 GHz
RAM: G.SKILL Ripjaws 32 GB, DDR4 2400
Storage: OEM NVMe, 512 GB
```

**Comment by rndusr** [comment]
Could be #234.

Or it's one of the many race conditions stig suffers from.

**Comment by ian-s-mcb** [comment]
Closing this as #234 is the appropriate issue. I should have come across it in my search. Thank you!
