### ISSUE TITLE
Unable to add new torrents, timeout after 10s

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#237]
Not sure if this is a stig or transmission issue, but twice in the last week I suddenly can't add new torrents and I don't know why. It just times out repeatedly, can't add anything new it seems. I even deleted 1000 torrents last time it happened in case things were just too overloaded, but it's happening again now not long after. I don't know why/how it started working again before. I've reinstalled stig-git from the AUR and restarted the transmission service.
stig version: 0.12.5a0
transmission version: 4.0.3

Have you run into this? Do you have any ideas? The torrents in question are from a private tracker, so I can't share the exact links. I'm currently trying to add two things that released recently and both just give a timeout error after a bit.

**Comment by Soundtoxin** [comment]
Okay, torrents are adding again now. I haven't changed anything in the past 10-15 minutes or whatever, so not sure why. Will leave this open in case you have any insights still.

**Comment by rndusr** [comment]
I haven't run into timeouts.

Have you tried increasing connect.timeout?

**Comment by Soundtoxin** [comment]
Had never looked into that option before. I'll try setting it to 30 instead of 10. Thanks for the idea. I'll close this issue for now and if I have problems again I'll re-open.

**Comment by Soundtoxin** [comment]
I have started running into problems with the 30 second timeout recently, not sure why. Could it be a transmission update with worse performance?

**Comment by Soundtoxin** [comment]
I even doubled the timeout to 60 and it still can't add a torrent. This is horrible.

**Comment by rndusr** [comment]
Which Transmission version are you running?

Can you add torrents with transmission-remote?

**Comment by Soundtoxin** [comment]
Transmission 4.0.6. I forgot to try another frontend. I ended up removing like 300 (had a little under 2k) torrents and restarting the daemon 2 or 3 times. Eventually got my couple torrents I needed to start. I set timeout back to 30 and got something to work still. Unsure if anything I did made a difference. If it starts timing out again I will try transmission-remote.
BTW I actually have stig and transmission both running on the same remote server I ssh into, so the timeouts are essentially a local (to the server) problem, not even related to the network. Very strange to me. I can move around the TUI and remove torrents freely but adding stuff kept timing out.

**Comment by rndusr** [comment]
It's possible Transmission is not accepting the torrents for some reason but not reporting any error
back. I think I've had a similar issue with misconfigured file system permissions a while back.

If you get timeouts again, run transmission-daemon with verbose logging and take a look at the logs.
