### ISSUE TITLE
About tui.theme

### ISSUE THREAD

**Issue by aabbccddeeffggj** [rndusr/stig#243]
Hi, in the default theme file it's said the following:

> You can also use RGB colors in the format "#RGB" (e.g. "#f00" for red, "#0f0"
> for green and "#00f" for blue).  They are converted to the closest color in
> the 256-color palette

By reading this I thought the 256 color palette was available, but it doesn't seem to be the case (for me at least).
I used both the 3 digits and 6 digits through the RGB format.

I'd like to ask whether it supports 256 colors palllete or not.

Thanks.

Edit: I have read more closely and indeed, it has support for 256 colors, so maybe I'm not doing something right, or it's something else.

**Comment by rndusr** [comment]
Works for me.

test.theme:

    tabs.peerlist.unfocused       #0f0   on #00f
    tabs.peerlist.focused         #fff   on #000

Load it with:

    $ stig set tui.theme test.theme and tab lsp and tab ls active

Which terminal are you using? Can you try a different one?

(Take your time with an answer. I'll be AFK until Monday.)
