### ISSUE TITLE
How would I go about configuring ?

### ISSUE THREAD

**Issue by throwaway217** [rndusr/stig#25]
Transmission has always been confusing for me because certain daemon settings are replicated in client configuration and it's really not clear at all how it's best to handle stuff. I see this does not depend on transmission but I assume it requires transmission-cli daemon right and it will respect it's settings ?

**Comment by rndusr** [comment]
The daemon stores its config in `~/.config/transmission-daemon/settings.json`. You can edit that file manually while the daemon is stopped (the daemon writes its config to that file when it terminates). Or you can use any of the clients for the daemon.

With stig, daemon settings are regular settings that start with "srv.". Get a list of all settings with `stig -h cfg`. There just aren't many yet. Feel free to make requests for what you're missing.

In the meantime, use `transmission-remote`, it should support most daemon settings.

**Comment by throwaway217** [comment]
Please allow me to describe my use case since I lack the knowledge to properly express what I need.

I'm basically looking for something which starts all my torrents and updates all trackers when I start my window manager/session with which I can interact with in a similar fashion I use the rtorrent client. I know I can daemonize rtorrent in some ways but I need UPnP and the transmission daemon seems to solve the first part of my problem. Since transmission-remote-cli is no longer developed that leaves me with stig and tremc and I think stig would be a better for me.

**Comment by rndusr** [comment]
I'm sorry, I don't really understand your question. Do you mean you want to start Transmission when you login?

**Comment by throwaway217** [comment]
I think yes but daemonized with no actual interface showing up.

**Comment by rndusr** [comment]
Just run `transmission-daemon`. But don't just put it in your `~/.xsession` because it doesn't have any mechanisms to stop you from running multiple instances. You would get another daemon process for every time you login while the old ones keep running. How to handle that best depends on your OS and init system.

**Comment by throwaway217** [comment]
I see, thanks for the tip and all the help. Have a nice and productive day :)

**Comment by rndusr** [comment]
You too. (:
