### ISSUE TITLE
configuration dir and file not created when not there

### ISSUE THREAD

**Issue by InfiniteProductions** [rndusr/stig#3]
On first run, stig could/should create a dummy configuration file and all needed path. It doesn't for now.

Also, please note that $HOME/.config/stig/rc is rather unusual, '.config' is far too much generic name and it should be '.stig' (you may take a look at the FHS for such choice).

**Comment by rndusr** [comment]
A new config file would be empty, so it's pointless to create one.

The default config file path follows the XDG Base Directory Specs.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

If you want a different path, you can set XDG_CONFIG_HOME or create an alias,
for example: `alias stig="command stig --rcfile ~/.stig"`

**Comment by InfiniteProductions** [comment]
> A new config file would be empty, so it's pointless to create one.

Not always, look at most of typical Unix programs, they comes with a default configuration or they create a new one inside the homedir of the caller the first time they're launched.

Default cfg should contains fair enough default values with explanations users can tweak according to their own tastes & needs.

An example with stig could be default host/port + username/password for transmission daemon, also includes download path, and maybe a directory where to put new torrent file to process.
With this default, user would be able to edit the file, adjust values according to the settings they have used for transmission. Stig could also read transmission daemon config file to fill its own.

**Comment by rndusr** [comment]
A config file that sets default values would needlessly slow down the already
slow startup process, especially if it sets server settings.

Creating a default config file that ships with the application but is not used
by default would be better. But I don't see the point. You get a nice list of
all the settings and what they do with `stig help settings`.
