### ISSUE TITLE
Option to change keybindings through settings file

### ISSUE THREAD

**Issue by logaritmisk** [rndusr/stig#30]
Hi!

I have a small issue with the new change that alt-enter opens the file list. I use OS X and Terminal.app, and the alt key isn't used be default. I could enable it, but that would mess up the rest of my workflow (I'm used to alt not being alt :)).

So it would be great if I could specify my own keybindings somehow.
There is other keybindings I would like to change as well, so it's not only for my alt-key laziness/problem :)

I could look into this myself, but not sure how you would like the syntax for keybindings to be.

Maybe something like this?

`set tui.bind 'context:torrent' 'key:alt-enter' 'action:tab filelist'`

**Comment by rndusr** [comment]
You can already change keybindings with the commands `bind` and `unbind`.
`stig help bind` and `stig help unbind` should explain everything.

**Comment by logaritmisk** [comment]
Ah maaan, and I though I looked everywhere.

Thanks for quick answer. Worked like a charm :)

**Comment by rndusr** [comment]
I'm curious why you didn't find those commands. Where did you look? Do you have
any suggestions what would've helped you?
