### ISSUE TITLE
Silly undocumented RC path on macOS

### ISSUE THREAD

**Issue by sometoby** [rndusr/stig#31]
On macOS, stig tries to read its RC file from `~/Library/Application Support/stig/rc`. Since stig uses appdirs to generate config file paths, I assume this behavior is intentional.

Besides the macOS config path being annoyingly long to type, it would be much saner if stig tried to read `~/.config/stig/rc` first and `~/Library/Application Support/stig/rc` was a fallback if used at all. I spent a disappointing amount of time trying to find out why stig was trying to connect to localhost despite srv.url being set in `~/.config/stig/rc` and only found out it wasn't reading that file because I lowered the default logging level in `logging.py`.

**Comment by rndusr** [comment]
Sorry for the confusion. My intention is to follow the specs. Do you think appdirs is doing the wrong thing? I'm not familiar with MacOS at all. Do you have a link to documentation?

BTW: stig has a debugging option: `--debug MODULE` (e.g. `stig --debug settings.rcfile`)

**Comment by sometoby** [comment]
Some searching turned up the [The Mac Application Environment](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html), see table 1-1.

To be clear, this might be a bike shed concern. The current behavior is correct according to the specification, however I think this platform-specific config location isn't adding much besides „correctness“ for the price confusion and inconvenience to users.

**Comment by rndusr** [comment]
The only real problem I see here is that the README is wrong because it mentions
`~/.config/stig/rc` as the default directory. I'll definitely change that.

I'm not so sure about straying away from the specs. As a user, I'm more annoyed
by applications that do their own thing, leaving me with a mess of different
systems, than by an imperfect spec.

Is it common for MacOS apps to ignore the specs and use `.config` instead? I
don't want stig to be the only one to create an out-of-place `~/.config`
directory.

**Comment by sometoby** [comment]
It is not common for native macOS apps to ignore the specs, but many CLI/TUI programs use their own respective defaults. Examples of such programs are OpenSSH, Vim, Neovim, Wireshark and WeeChat. There are lots more.

As for an out-of-place .config directory: I'll bet that most if not all stig users on macOS will find `~/Library/Application Support` more unexpected or surprising of a path for stig's rc file than `~/.config`. Stig isn't a native macOS app like you'd find on the App Store; I don't think it's reasonable for it to behave like one.

**Comment by rndusr** [comment]
OK, if the spec isn't used by unixy apps, it should be hardcoded to
`~/.config/stig/rc` on macOS.  Thanks for taking the time to change my mind.

**Comment by rndusr** [comment]
Would you do the implementation? I don't have a mac for testing.

You only have to change the value of `DEFAULT_RCFILE` in `settings/defaults.py` based on the detected OS.

**Comment by sometoby** [comment]
Sure, no problem! I'll send a PR soon-ish.

**Comment by rndusr** [comment]
On second thought, I think it would be better to not detect the OS at all and just use the XDG spec everywhere, basically: `DEFAULT_RCFILE = $XDG_CONFIG_HOME/stig/rc` where XDG_CONFIG_HOME defaults to `~/.config` if not set.

**Comment by sometoby** [comment]
Makes sense. I'll implement it as such.

**Comment by rndusr** [comment]
On third thought, there's https://pypi.python.org/pypi/xdg/, which is a much simpler implementation than appdirs. Please use that.
