### ISSUE TITLE
Question about adding torrents

### ISSUE THREAD

**Issue by peaveyman** [rndusr/stig#35]
Is there a way to change the location a torrent will be saved to? Most of what I download go in the default location but a select few need to go in another location. 

Also, when adding is there a way to rename it?

**Comment by rndusr** [comment]
It's in the help for the `add` command:

```
    $ stig -h add
    [...]
    --path,-p <PATH>  Custom download directory for added torrent(s)
```

Renaming a torrent is not supported yet. (Contributions are welcome.)

**Comment by peaveyman** [comment]
Would the mv command work for renaming it?

**Comment by rndusr** [comment]
No, that just moves the torrent to a different path.

**Comment by peaveyman** [comment]
What about if I rename the torrent before adding it? Does it add it with the torrent name or does it use something that's in the torrent file?

**Comment by rndusr** [comment]
The name of the torrent file is irrelevant. The names of the files of the actual content are specified in the torrent.
