### ISSUE TITLE
Unformatted tabs on Arch

### ISSUE THREAD

**Issue by hhiru** [rndusr/stig#38]
I copied the config file in the README but I have unformatted parameters in the tabs. It looks different from the screenshot in the README and in particular the lines
```
!progress,path,!rate
!progress --columns name,progress,ratio,size
```
are parsed literally showing {!progress,path,!rate} and {!progress} in the title.

I'm on Arch and I installed stig from the AUR

**Comment by rndusr** [comment]
Those are the sort orders. It's not a bug, it's a feature! :)

Eventually there will probably be arrows pointing up or down in the corresponding columns.

But it's possible to sort by values that don't have a corresponding value (e.g. `ls --columns name,progress --sort ratio`). At least in that case, the sort orders should still be visiable somewhere.
