### ISSUE TITLE
"B" column when enabling "size" column in settings

### ISSUE THREAD

**Issue by hhiru** [rndusr/stig#42]
What is this column? I'd like to enable only the size column
![image](https://user-images.githubusercontent.com/11262717/32980470-27138294-cc67-11e7-8611-beb7fc08a736.png)

**Comment by rndusr** [comment]
It's part of the "size" column header. The "B" stands for "bytes". You can set
unit.size to "bit" and it will change to "b".

Headers display the label on the left and the unit on the right.
