### ISSUE TITLE
No stig command after installation

### ISSUE THREAD

**Issue by hhiru** [rndusr/stig#47]
No matter if I install it globally or locally, it can't find the stig command. I'm using latest stable Debian.
I tried installing with `--user` option first, then from the latest github branch and finally globally but same results

> $ sudo pip3 install stig 
> [sudo] password for hiru: 
> Requirement already satisfied: stig in /root/.local/lib/python3.5/site-packages
> Requirement already satisfied: urwid>=1.3.0 in /root/.local/lib/python3.5/site-packages (from stig)
> Requirement already satisfied: urwidtrees>=1.0.3dev0 in /root/.local/lib/python3.5/site-packages (from stig)
> Requirement already satisfied: natsort in /root/.local/lib/python3.5/site-packages (from stig)
> Requirement already satisfied: pyxdg in /usr/lib/python3/dist-packages (from stig)
> Requirement already satisfied: blinker in /root/.local/lib/python3.5/site-packages (from stig)
> Requirement already satisfied: aiohttp>=0.22.5 in /root/.local/lib/python3.5/site-packages (from stig)
> Requirement already satisfied: mock in /root/.local/lib/python3.5/site-packages (from urwidtrees>=1.0.3dev0->stig)
> Requirement already satisfied: yarl>=0.11 in /root/.local/lib/python3.5/site-packages (from aiohttp>=0.22.5->stig)
> Requirement already satisfied: multidict>=3.0.0 in /root/.local/lib/python3.5/site-packages (from aiohttp>=0.22.5->stig)
> Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from aiohttp>=0.22.5->stig)
> Requirement already satisfied: async-timeout>=1.2.0 in /root/.local/lib/python3.5/site-packages (from aiohttp>=0.22.5->stig)
> Requirement already satisfied: pbr>=0.11 in /root/.local/lib/python3.5/site-packages (from mock->urwidtrees>=1.0.3dev0->stig)
> Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from mock->urwidtrees>=1.0.3dev0->stig)
> Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl>=0.11->aiohttp>=0.22.5->stig)
  

> $ stig
> -bash: stig: command not found

**Comment by rndusr** [comment]
With `--user` the executable should be in `~/.local/bin`.

I'll try to reproduce the issue later.

**Comment by hhiru** [comment]
no `bin` folder in my `.local`

**Comment by rndusr** [comment]
Ah, sorry, I should've seen that right away. You're installing into root's home.
Note the `/root/.local/...`:

```
Requirement already satisfied: stig in /root/.local/lib/python3.5/site-packages
```

That's because you use `sudo`. If you want to install globally, just don't use
the `--user` switch. It should install in `/usr/local`.

**Comment by hhiru** [comment]
I tried using `sudo pip3 install stig` again but same problem

> $ cd /usr/local
> $ ls
> total 32
> drwxrwsr-x  2 root staff 4096 Jan  9 21:53 bin
> drwxrwsr-x  2 root staff 4096 Jan  9 14:59 etc
> drwxrwsr-x  2 root staff 4096 Jan  9 14:59 games
> drwxrwsr-x  2 root staff 4096 Jan  9 14:59 include
> drwxrwsr-x  4 root staff 4096 Jan  9 15:04 lib
> lrwxrwxrwx  1 root staff    9 Jan  9 14:59 man -> share/man
> drwxrwsr-x  2 root staff 4096 Jan  9 14:59 sbin
> drwxrwsr-x 13 root staff 4096 Jan  9 21:33 share
> drwxrwsr-x  2 root staff 4096 Jan  9 14:59 src
> $ find stig
> find: ‘stig’: No such file or directory

**Comment by hhiru** [comment]
I tried using sudo `pip3 uninstall stig` and then `pip3 install stig` and now it correctly add stig to `.local/bin` but I can't run stig by simply typing `stig`. need to use the `.local/bin/stig` path to launch it. Is this intended behavior? Do I need to add `.local/bin` to `$PATH`?

**Comment by rndusr** [comment]
Try `pip3 install stig` without `sudo`.

**Comment by rndusr** [comment]
Yes, you need to add `$HOME/.local/bin` to your `PATH`.
