### ISSUE TITLE
Set tmux title to "stig"

### ISSUE THREAD

**Issue by kutsan** [rndusr/stig#49]
Currently, title would be `Python` which is ugly. You can set the tmux title to `stig` with this escape sequences.

```sh
printf '\033k%s\033\\' 'stig'
```

This code only works if `allow-rename` option in `tmux` set to `on`, default is `off`. You can set this in `tmux.conf`.

```sh
set-option -g allow-rename on
```

Also, there is a environment variable `$TMUX` that you can check if `tmux` is open.

[ranger](https://github.com/ranger/ranger) provides [an option](https://github.com/ranger/ranger/blob/b1e08bf5b52746da2f0e5d9995e8dbc8c8505f62/ranger/config/rc.conf#L145-L146) for that, maybe you can provide too. But actually, I don't think extra flag is necessary, since if you set that `tmux` option to `on`, this will be what you expected.

**Comment by rndusr** [comment]
I've got it working, but there doesn't seem to be a way to reset the title when
stig terminates. ranger doesn't seem to reset the title either, so that probably
means it's a common issue?

**Comment by kutsan** [comment]
Hmm, actually that title works fine with ranger. When ranger open, it shows `ranger`, when I exit it it becomes `zsh` again.

I found these:

- https://github.com/ranger/ranger/issues/228
- https://github.com/ranger/ranger/commit/f6fca81a9a3ab58f4838cf22fb7fb7d2f3240313
- [ranger/gui/ui.py#L126](https://github.com/ranger/ranger/blob/f6fca81a9a3ab58f4838cf22fb7fb7d2f3240313/ranger/gui/ui.py#L126).

**Comment by rndusr** [comment]
So ranger is getting and setting tmux options and keeping track of them while it
runs. I don't like that approach. In my opinion, resetting the title should be
implemented in tmux, e.g. by offering another escape sequence.

**Comment by kutsan** [comment]
I don't like that approach either but for now it's better than nothing. I don't know why but this is works like that for years. If you have enough motivation, you should better open a issue at tmux repository.

**Comment by kutsan** [comment]
Or maybe @ThomasAdam or @nicm can help us(?).

**Comment by nicm** [comment]
The \033k sequence does not set the terminal title but renames the tmux window. It is a screen extension and we are not going to add any more extensions to undo it.

I would suggest instead that your program changes its process name in the kernel with setproctitle/argv manipulation/whatever is needed on your supported platforms, then tmux automatic-rename will pick it up.

If you actually wanted to set the title you can use the OSC 0/2 sequences, recent tmux supports the xterm title stack which does give a way to undo it. But I guess you are after the name not the title.

**Comment by kutsan** [comment]
I tested `setproctitle` package now with a single, simple program but seems like it only changes what I see inside `top`, `htop` or `ps`. `tmux`s title still persists as `Python`.

I know I can change terminal title but I don't care about that; I don't even use title bar, so that does nothing for me. The problem for me that `Python` should be `stig`. 

![](https://i.imgur.com/XRQZaRo.png)

Actually, it's okay if you implement that without resetting it when `stig` is exited, if you don't want to track tmux options as `ranger` developers did. Since, it's always stay like that, I don't close that tab much often.

**Comment by kutsan** [comment]
By the way, thank you for spending your time to answer @nicm. We appreciate it.

**Comment by nicm** [comment]
It probably just uses prctl rather than changing argv so that /proc changes
(tmux itself does this as well because changing argv is a pain)

**Comment by kutsan** [comment]
@nicm Yes, seems like you are right, it uses `prctl`.

What do you think about ranger's solution for that topic? Do you think it's the way to go, keeping track of tmux options while program is running? I've looked around and everyone suggests `setproctitle` to changing process name kernel-wise but that doesn't work as I said. What should we do?

**Comment by nicm** [comment]
You need to change the process name by modifying argv[0] instead of using
prctl.

**Comment by kutsan** [comment]
I didn't pay attention that you're answering through e-mails but I should have said this project is Python-based and modifying `argv[0]` in Python does nothing. Other solutions are not portable nor easy and I'd like to point out the fact there is no clear API in `tmux` for that. I know `\033k` sequence comes from `screen` and there is no reason to extend it but still, we can change through that sequence but we can't turn it back and it's pain. In fact, we might don't want to change process name but only tmux's window title.

Sorry to interrupt you for that.

**Comment by nicm** [comment]
Right but it is not up to the process to set the window name, the name is
there for the user to set (unlike the title). That's why allow-rename is
now off by default (and I seriously considered removing the escape sequence
entirely). tmux sets the window name automatically to the process name as a
convenience.

If you can identify the process by some other method, you as a user could
tweak automatic-rename-format to detect it and use the name you prefer. I
do that to remove version numbers from programs that include them in their
name.





On 21 Jan 2018 8:19 pm, "Kutsan Kaplan" <notifications@github.com> wrote:

I didn't pay attention that you're answering through e-mails but I should
have said this project is Python-based and modifying argv[0] in Python does
nothing. Other solutions are not portable nor easy and I'd like to point
out the fact there is no clear API in tmux for that. I know \033k sequence
comes from screen and there is no reason to extend it but still, we can
change through that sequence but we can't turn it back and it's pain. In
fact, we might don't want to change process name but only tmux's window
title.

Sorry to interrupt you for that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rndusr/stig/issues/49#issuecomment-359277368>, or mute
the thread

**Comment by nicm** [comment]
It would be nice if tmux could get the name set by prctl on Linux, I'd need
to have a look and see where that goes.

**Comment by rndusr** [comment]
@nicm, thanks a lot for helping out.

@kutsan, setproctitle actually works fine for me. There's just a small delay
when I close stig before the window name is reset.

**Comment by kutsan** [comment]
@nicm Thanks again for once more. I suggest you to unsubscribe from this issue, we don't want to spam you further more.

@rndusr I now tested it on Android, GNU/Linux and macOS. It doesn't work on macOS, others are fine. My initial argument was tmux should provide a clean API for that among with escape sequences but seems like that won't happen. So, what'll you do, abandon macOS users and go with setproctitle or the solution ranger did. And I believe that delay comes from `status-interval` option which is normal I think.

**Comment by rndusr** [comment]
I've implemented the setproctitle solution for now. It seems to be the cleanest
solution. If setproctitle doesn't work on macs, that seems to be a bug in
setproctitle.

**Comment by kutsan** [comment]
@rndusr `setproctitle` actually works, I can clearly see process name changes in the output of `ps` but tmux's window title stay as is. Not sure where the problem is.

**Comment by rndusr** [comment]
My `~/.tmux.conf` looks like this:

    set-window-option -g automatic-rename on

Does that help?

**Comment by kutsan** [comment]
I believe its default is on if you don't set window title while creating. Still, I tried it with that line but doesn't work. By the way, as a side not, my OS version is 10.12.6.

**Comment by rndusr** [comment]
Oh, are you talking about MacOS? I don't have that. I'm on Debian testing.

**Comment by kutsan** [comment]
Yes, I am sorry if it wasn't clear enough. `setproctitle` works okay under Linux, there is no problem for that, even on Android somehow works. That Mac problem may be related to this https://github.com/dvarrazzo/py-setproctitle/issues/10.

**Comment by kutsan** [comment]
So, https://github.com/rndusr/stig/commit/5bf178ee8bb0eb33f39345cae9a1c3798585837b closes this issue.

**Comment by kutsan** [comment]
Thanks also @rndusr for spending your time! I'm glad.
