### ISSUE TITLE
Missing dependency urwidtrees

### ISSUE THREAD

**Issue by Nicd** [rndusr/stig#5]
First of all, very cool project! `transmission-remote-cli` kept crashing for me, but this looks really nice.

Looks like you're missing the dependency `urwidtrees` in your setup and that leads to crashes. I fixed it myself in my virtualenv with `pip install urwidtrees`.

**Comment by rndusr** [comment]
> First of all, very cool project! `transmission-remote-cli` kept crashing for me, but this looks really nice.

Thanks! :)

> Looks like you're missing the dependency `urwidtrees` in your setup and that leads to crashes. I fixed it myself in my virtualenv with `pip install urwidtrees`.

Sorry. I added it to the README but forgot the setup.py.
Should be fixed in the latest commit.

**Comment by Nicd** [comment]
Can confirm that it works! 👍
