### ISSUE TITLE
Display country flags as emoji in peerlist

### ISSUE THREAD

**Issue by kutsan** [rndusr/stig#50]
My idea is, instead of showing 2-letter country codes, to show them as emoji.

Also, there is a Python package https://pypi.python.org/pypi/emoji-flags for that. You can make it optional beside `geoip`.

**Comment by rndusr** [comment]
Do you know a font that implements flags?

**Comment by kutsan** [comment]
I think [this](https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols) page would help.

**Comment by rndusr** [comment]
Closing this since IP geolocation has been removed.
