### ISSUE TITLE
Add custom urwid-widgets to official urwid repository

### ISSUE THREAD

**Issue by kpj** [rndusr/stig#53]
Hello,

I noticed a few quite useful urwid-widgets (such as eg Scrollable) in the [TUI section](https://github.com/rndusr/stig/tree/master/stig/tui).
In order to make it easier for others to use these as well, what do you think about adding them to the official [urwid repository](https://github.com/urwid/urwid) as a PR?
I feel like they would make a great addition.

**Comment by rndusr** [comment]
Thank you.

I'd be happy to contribute my stuff upstream, but I'm not sure it integrates
well.

`Scrollable` and `ListBox` may be closest, but they also have issues. For
example the fact that `Scrollable` needs to know the total number of lines a
widget needs for a given width, which a `ListBox` doesn't keep track of, so I
have to render the complete listbox contents every time I want to render the
scrollbar. I don't want to make a PR unless this is fixed, and I couldn't figure
out a way, but if you want to get your hands dirty, I'd be happy to help where I
can.

There is also an issue with moving focus to invisible items. I forgot the
details, but there is be a (hopefully somewhat coherent) comment somewhere in
`scroll.py`.

**Comment by kpj** [comment]
I looked at `Scrollable` in a little more detail and tried out a slightly non-trivial example:
```python
import urwid

from scroll import Scrollable, ScrollBar


bg = urwid.SolidFill('+')

content = urwid.Text(str(list(range(10000))))
scroll = ScrollBar(Scrollable(urwid.LineBox((content))))

overlay = urwid.Overlay(
    scroll, bg,
    align='center', width=('relative', 75),
    valign='middle', height=('relative', 75))

loop = urwid.MainLoop(overlay)
loop.run()
```
For me, this seems to work perfectly:
![screen shot 2018-02-22 at 12 32 13 pm](https://user-images.githubusercontent.com/645279/36536220-71a7704e-17cc-11e8-9485-e1f910d1107d.png)
So I am not entirely sure whether the "total number of lines"-problem is specific to `ListBox ` or a more general concern.
Could this be related to the way different widget types (box, flow, fixed) need to be nested?

**Comment by rndusr** [comment]
I didn't say it doesn't work, I said it's very inefficient. And that's only a
concern with `ListBox` AFAIK due to its implementation.

**Comment by kpj** [comment]
Ah, I see. Thanks for the clarification.

Do you think that opening an issue with `urwid` itself would be reasonable?
They might have some useful advice.

**Comment by rndusr** [comment]
My original urwid issue is here: https://github.com/urwid/urwid/issues/226

That's also the more appropriate place to discuss this, so I'm going to close
this one.
