### ISSUE TITLE
Add column name 'comment' to list --columns

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#58]
I'm not sure how much this would be generally useful, but I installed stig specifically because I need to extract the **comment** from a torrent, which I imagined I could do like this:

```
stig ls -c comment id=<torrent-id>
```

Looking at `stig help ls` I could see column **comment** is not available for selection. I can see I could run `stig info <filter>` and then filter out the `Comment: ` line, but selecting the field in `stig ls -c` feels more natural.

Let me explain why I need **comment** so that you see if that column might deserve to be included: I set up a script to be run when a torrent completes, that hard links any video files (mp4, mkv, avi, srt) to a _~/watch_ directory. Quite frequently I send video files to my father using torrents: I create a torrent with the file/directory to send, add the torrent so that it starts seeding right away, and send him the torrent. The side effect is: as the torrent contents are already 100% present when I add the torrent, transmission triggers the script and hard links the video files to _~/watch_. So I need a way to identify these torrents  that I created myself (for the purpose of sending files to my father) and don't hard link their video files. transmission only makes this information available to scripts: torrent name, id, hash, download directory, time it completed. Based on this information, I can't differentiate the torrents I created from the torrents I added from elsewhere. Therefore I thought of adding a comment with my name when I created my torrents, and then, in the transmission script, I would look at the comment: if it contained my name, I wouldn't hard link the video files to _~/watch_.

**Comment by marcelpaulo** [comment]
Oh, just discovered something about stig which is very useful: when the output from a command is not a tty, it changes to a parsable format, so that I could get the **comment** column with:

```
stig info 'name=foo' | awk '/^comment/ { print $2 }'
```

So I can get what I need this way. But anyway, I still feel it might be valid to add **comment** to the selectable columns in `stig ls`.

**Comment by rndusr** [comment]
The tricky part about a 'comment' column is that comments can contain
newlines. Technically, it shouldn't break anything if a torrent uses multiple
lines instead of just one, but it would probably make the list much harder to
read.

**Comment by marcelpaulo** [comment]
Oh, I see, I didn't know that. It doesn't look like it's worth it to implement this, even more so since the information can be obtained with `stig info`.

Thanks for the swift reply, @rndusr, and the clarification !
