### ISSUE TITLE
Country code not shown for IPv6 peer addresses

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#59]
I've installed stig from source this morning and I'm really impressed by it. I don't know how I stumbled across stig but definitely it should be mentioned in the transmission project site/wiki that it's undoubtedly the best ncurses/cli transmission client, hands down !

I've just noticed that, although **GeoIP** is installed, country codes are not shown for IPv6 peer addresses. For instance, this is a snapshot of my currently transmission torrent list:

![screenshot_2018-03-14_10-52-42](https://user-images.githubusercontent.com/10074769/37406672-79d9fbce-2776-11e8-96a5-ef8a87675655.png)

I know that the IPv6 address in the list is in Brazil, but the country code is not shown. I had a look at the [maxmind web site](https://support.maxmind.com/ipv6-data-faq/), and they say that **GeoIP legacy** should be able to lookup IPv6 addresses.

My current stig version is **0.8.3a**, and the GeoIP version I have installed is:

```
Name: GeoIP
Version: 1.3.2
Summary: MaxMind GeoIP Legacy Database - Python API
Home-page: http://www.maxmind.com/
Author: MaxMind, Inc.
Author-email: support@maxmind.com
License: GNU LESSER GENERAL PUBLIC LICENSE
		       Version 2.1, February 1999
Location: /home/paulo/.local/lib/python3.6/site-packages
```

**Comment by rndusr** [comment]
Thank you for your kind words. stig is currently still in alpha stage and I'm
still experimenting and learning, so I don't think it should be an official
client. But I hope stig will eventually get a link on the Transmission website.

I just tried it and I get a non-fatal error printed into the TUI that says:

"Invalid database type GeoIP Country Edition, expected GeoIP Country V6 Edition"

The IPv6 country code still was unknown.

There doesn't seem to be a geoip database package that explicitly supports IPv6.
Not sure what to do about that.

**Comment by marcelpaulo** [comment]
I was looking around the Ubuntu packages currently installed in my laptop, and **geoip-database** seems to be the one with the databases. Here's its content:

```
/.
/usr
/usr/share
/usr/share/GeoIP
/usr/share/GeoIP/GeoIP.dat
/usr/share/GeoIP/GeoIPv6.dat
/usr/share/doc
/usr/share/doc/geoip-database
/usr/share/doc/geoip-database/changelog.Debian.gz
/usr/share/doc/geoip-database/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/geoip-database
```

I don't know how's the Python code to lookup the country codes, but I get the impression that, if the IP address is v6, _/usr/share/GeoIP/GeoIPv6.dat_ should be used, and not _/usr/share/GeoIP/GeoIP.dat_. But then again, I don't know if the Python code opens these databases explicitly.

Searching for Ubuntu packages with python3 and geoip in the name resulted in only 2 packages:

- python3-geoip
- python3-geoip2

Searching pip packages with geoip in the name (`pip3 search geoip`) brought loads of packages, but these seemed to be the only relevant ones here, although my ignorance of Python might have made me overlook something:

- GeoIP (the one I installed)
- geoip2
- pygeoip
- simplegeoip2

As there doesn't seem to be any IPv6-specific package, it looks as though there might be either some kind of IPv6-lookup specific method, or the IPv6 database has to be opened explicitly to lookup IPv6 addresses. I wish I knew Python to investigate this further.

**Comment by marcelpaulo** [comment]
On a side note, in order to install **GeoIP**, I had to install Ubuntu package **libgeoip-dev**. I don't know if it also has to be installed in case GeoIP is installed as part of the stig install, as you suggest in the build instructions.

**Comment by marcelpaulo** [comment]
The MaxMind [repository](https://github.com/maxmind/geoip-api-python) for the Python API has no documentation whatsoever, but looking at the [code](https://github.com/maxmind/geoip-api-python/blob/master/py_GeoIP.c), I can see that there seems to be different functions to lookup country code base on IPv4 and IPv6 addresses:

```
GeoIP_country_code_by_addr_Py
GeoIP_country_code_by_addr_v6_Py
```

Actually, for all lookup functions, there are 2 versions, one suffixed `_Py` and the other `_v6_Py`, the first I presume should be used for IPv4 addresses, and the second for IPv6 addresses.

So the solution may be to determine if the peer address is IPv4 or IPv6, and then call the appropriate function to look up the country code.

**Comment by rndusr** [comment]
Thanks for investigating.

I think you're right and I have to open a separate database for IPv6 lookups.

But according to the examples[1], I have to explicitly provide the path to the
IPv6 DB, which I can't know. For IPv4, I can just use `GeoIP.new()` and it
magically finds the v4 DB.

I'm trying to understand the relevant C code, and it seems to me the IPv4 DB
file path is so obvious it doesn't need to be specified anywhere.[2][3]

It would be best to just use GeoIP2, but IIRC, I couldn't figure out how to do
this in a user-friendly way, i.e. without users having to manually download and
install databases from maxmind.

[1]: https://github.com/maxmind/geoip-api-python/blob/master/examples/v6.py
[2]: https://github.com/maxmind/geoip-api-python/blob/master/py_GeoIP.c#L82
[3]: https://github.com/maxmind/geoip-api-c/blob/master/libGeoIP/GeoIP.h#L172

**Comment by rndusr** [comment]
Yes, that's because the python package is actually written in C and to built it,
you need the headers.

If you install `python3-geoip` via your package manager, you can remove
`libgeoip-dev`.

**Comment by marcelpaulo** [comment]
> I think you're right and I have to open a separate database for IPv6 lookups.

I'm feeling that I was wrong and there's no need to explicitly open any database, and, as you said:

> I can just use `GeoIP.new()` and it magically finds the v4 DB

perhaps the module magically finds the right DB depending on which function was used for the lookup:

For IPv4 => `country_code_by_addr`
For IPv6 => `country_code_by_addr_v6`

I googled a bit and found out that there's a Python module that validates an IP address and returns its version. Here's the snippet I stumbled across:

```python
import ipaddress
import sys

try:
   ip = ipaddress.ip_address(sys.argv[1])
   print '%s is a correct IP%s address.' % (ip, ip.version)
except ValueError:
   print 'address/netmask is invalid: %s' % sys.argv[1]
except:
   print 'Usage : %s  ip' % sys.argv[0]
```

So, perhaps _client/geoip.py_ would need to be changed to:

1. Determine the version of the IP address
1. If it's v4, lookup the country code with `_geoip.country_code_by_addr`
1. If it's v6, lookup the country code with  `_geoip.country_code_by_addr_v6`

> If you install `python3-geoip` via your package manager, you can remove `libgeoip-dev`

Thanks for the clarification !

**Comment by rndusr** [comment]
> I'm feeling that I was wrong and there's no need to explicitly open any database

That's what I thought, but that gives me the "Invalid database type" message.

If I load a separate DB from `/usr/share/GeoIP/GeoIPv6.dat` and use that on
addresses that have ':' in them, everything seems to work as expected. But that
path is incorrect if you install GeoIP manually or don't use a Debian-based
distro.

I wish I could understand how the C library auto-discovers `GeoIP.dat`

**Comment by marcelpaulo** [comment]
> That's what I thought, but that gives me the "Invalid database type" message.

Yes ! Pardon my Python ignorance, I just modified that snippet I mentioned earlier:

```python
#!/usr/bin/env python3

import GeoIP
import ipaddress
import sys

try:
    addr = sys.argv[1]
    ip = ipaddress.ip_address(addr)
    print('%s is a correct IPv%s address' % (ip, ip.version))

    _geoip = GeoIP.new(GeoIP.GEOIP_MEMORY_CACHE)
    if ip.version == 6:
        country_code = _geoip.country_code_by_addr_v6(addr)
    else:
        country_code = _geoip.country_code_by_addr(addr)

    print('Country code for IPv%s address %s = %s' % (ip.version, addr, country_code))

except ValueError:
    print('address/netmask is invalid: %s' % addr)

except:
    print('Usage: %s ip' % sys.argv[0])
```

and indeed the result was:

```
paulo@monk:~/tmp$ ./x 2001:1284:f016:9a43:28d1:65f1:c1a0:a0e8
2001:1284:f016:9a43:28d1:65f1:c1a0:a0e8 is a correct IPv6 address
Invalid database type GeoIP Country Edition, expected GeoIP Country V6 Edition
Country code for IPv6 address 2001:1284:f016:9a43:28d1:65f1:c1a0:a0e8 = None
```
> If I load a separate DB from `/usr/share/GeoIP/GeoIPv6.dat` and use that on
> addresses that have ':' in them, everything seems to work as expected. But that
> path is incorrect if you install GeoIP manually or don't use a Debian-based
> distro.

It makes sense. There must be a solution that doesn't depend on hardcoding the the DB pathname. If only MaxMind had documented the GeoIP interface !

**Comment by rndusr** [comment]
This should work now as expected.

**Comment by marcelpaulo** [comment]
Wow, glanced through the commit: a low of sweat in this ! Yeah, it's working ! See below, _FR_ for an IPv6 address:

![image](https://user-images.githubusercontent.com/10074769/38100302-6b4b306c-3353-11e8-857e-b1cacbcf5b87.png)

Thanks for that !
