### ISSUE TITLE
Installation fails on OpenBSD 6.0 with Python 3.5.2

### ISSUE THREAD

**Issue by dennisvanderpool** [rndusr/stig#6]
Trying to install stage on OpenBSD 6.0 with Python 3.5.2 but i get an error during installation (regular install and git clone dev-install both give me the same error). Haven't spent a lot time trying to resolve it myself yet, will do it later if nobody gave me any hints/clues by then :-)

# uname -a  
OpenBSD torrentbox.local 6.0 GENERIC#2148 amd64

# python   
Python 3.5.2 (default, Jul 26 2016, 01:52:58) 
[GCC 4.2.1 20070719 ] on openbsd6

# pip3 install stig
Collecting stig
  Downloading stig-0.1.0a0.tar.gz (103kB)
    100% |################################| 112kB 201kB/s 
Collecting urwid>=1.3.0 (from stig)
  Using cached urwid-1.3.1.tar.gz
Collecting aiohttp>=0.22.5 (from stig)
  Using cached aiohttp-1.2.0.tar.gz
Collecting urwidtrees>=1.0.1.1 (from stig)
  Using cached urwidtrees-1.0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7q9we0i6/urwidtrees/setup.py", line 4, in <module>
        import urwidtrees.version as v
      File "/tmp/pip-build-7q9we0i6/urwidtrees/urwidtrees/__init__.py", line 6, in <module>
        from .decoration import DecoratedTree, CollapsibleTree
      File "/tmp/pip-build-7q9we0i6/urwidtrees/urwidtrees/decoration.py", line 4, in <module>
        import urwid
    ImportError: No module named 'urwid'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7q9we0i6/urwidtrees/

**Comment by rndusr** [comment]
That seems to be a bug in urwidtree's setup.py that is resolved in the latest
development version.

Please install from github and confirm/refute:

    pip3 install git+https://github.com/rndusr/stig.git@master

**Comment by ncoop** [comment]
I had this issue on Arch. urwidtree is failing to properly require urwid. Just install urwid first.

**Comment by rndusr** [comment]
I'm assuming this is resolved.
