### ISSUE TITLE
Changing local settings in the TUI doesn't change ~/.config/stig/rc

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#67]
I've just updated to master (3f29488cc8eeda107a7804a6bf44126d34c37ee6), and noticed, in the new tab `settings` in the TUI:

1. Toggling boolean `srv.*` settings changes them in the running transmission daemon. This is great !
1. I can change change `column.*` settings correctly, and it has effect on newly created tabs, but not on the current ones, and it doesn't change _~/.config/stig/rc_. Is this yet to be implemented, or is it a bug ?
1. Changing the `unit.*` settings does have immediate effect on all current tabs, but it doesn't change them on _~/.config/stig/rc_.

It's really great to be able to change the settings on the TUI. The toggling of boolean settings and settings which only have 2 possible values, such as `unit.bandwidth`, is really cool.

**PS:** Do you plan to implement something like the global tab `settings` but for individual torrents ?

**Comment by rndusr** [comment]
> 1. Toggling boolean `srv.*` settings changes them in the running transmission daemon. This is great !

Confirmed. :)

Changing column.* settings doesn't affect existing tabs because they can have
custom columns via the `--columns` options. It would probably be possible to
change only the columns in tabs with default columns, but that may not be
obvious to the user ("Why did that tab change its columns and that one
didn't?"), and I don't think it's especially useful.

stig never touches any rc file because rc files aren't config files. 'rc', in
this case, stands for Run Commands. It's just a list of arbitrary
commands. Changing an rc file would be unexpected (like running a bash script
shouldn't change the bash script) and likely to be very complicated and buggy
because commands can be quite complex (nested quotes, multiple lines, chained
commands, etc).

> **PS:** Do you plan to implement something like the global tab `settings` but for individual torrents ?

That's an interesting idea I haven't had yet. What would you expect to see
there? I can only think of per-torrent rate and peer limits at the moment. In
the future, there could be download location, peer limit, queue position, seed
ratio limit and seed idle limit. Am I missing something?

**Comment by marcelpaulo** [comment]
> Changing column.* settings doesn't affect existing tabs because they can have
> custom columns via the `--columns` options. [...] "Why did that tab change its columns and that one
> didn't?"

I hadn't thought of that, yes, you're right, it wouldn't be intuitive to do it.

> stig never touches any rc file because rc files aren't config files

I see your point, and it makes sense, but ... exposing those settings for change in the TUI does intuitively raise the expectation that the rc file would be changed to reflect it. I suspect that any user will instinctively think of the rc file as a config file, and ignore the finer implications that it's just "a list of arbitrary commands" as you explained.

Perhaps it might be more intuitive to allow changing only those settings that will survive the session, such as the `srv.*` ones. I'd risk that seeing changes not surviving the session will bite users, just as it bit me.

> What would you expect to see there? I can only think of per-torrent rate and peer limits at the moment. > In the future, there could be download location, peer limit, queue position, seed
> ratio limit and seed idle limit. Am I missing something?

That's precisely I had in mind. Actually I just rehashed what I had already asked for in #60.

**Comment by rndusr** [comment]
> I suspect that any user will instinctively think of the rc file as a config file, and ignore the finer implications that it's just "a list of arbitrary commands" as you explained.

Maybe you're right. You're actually the second user that thought this was a bug.

But config files that are auto-adjusted by the application usually consist of
simple `key = value` pairs. The only thing you can do in them is assign values
to variables.

stig's rc files are scripts. To assign a value to a variable/setting you have to
run a command. The same command you would provide manually as an argument or
type into the command prompt in the TUI.

This is a fundamental difference and one of the core design principles of stig
(everything is a command).

But I'll add a `dump <filename>` command at some point that might mitigate this
issue. It writes `set <setting> <value>` to a file for each setting that isn't
set to its default value. You could bind it it to a key (e.g. <alt-S>) that you
would press after you made changes in the TUI. But you would have to have your
settings in a separate file that stig can overwrite without killing your `tab`
commands and whatever else you have in there, and you would have to source that
from the default rc file (e.g. `bind <alt-S> dump ~/.config/stig/settings` and
add `rc settings` to `~/.config/stig/rc`).

**Comment by rndusr** [comment]
> stress this point in _README.org_ and/or in the output from `help rcfile`

I don't see how I can make this any clearer than it already is. But as the
author I'm also heavily biased.

As someone that didn't quite get it immediately, maybe you could phrase it
better? Feel free to make a pull request.

**Comment by marcelpaulo** [comment]
> As someone that didn't quite get it immediately, maybe you could phrase it
> better? Feel free to make a pull request.

I might not be fluent enough in git to make a pull request, but I'll give it a try in rephrasing it, and will post it here if I can't make the pull request.

**Comment by marcelpaulo** [comment]
OK, I confess, I wasn't able to rephrase your description of rc files in a way that a user like myself wouldn't misunderstand them like I did, I feel like I exchanged 6 for half a dozen :-(

Anyway, here's a [patch](https://pastebin.com/j9Ye2mQr) with my meagre rephrasing. My scant knowledge of git wasn't enough for a pull request (I'll get cracking with O'Reilly's _Version Control with Git_, and next time I promise I'll submit a pull request)

**Comment by marcelpaulo** [comment]
It just occurred to me: wouldn't it be more standard to name the rc file `stigrc` ? Thinking vim and vimrc ... I think I've never seen an rc file actually named `rc`.

**Comment by marcelpaulo** [comment]
> I chose 'rc' over 'stigrc' because it resides in ~/.config/stig, so it's already clear to which application it belongs

That's what I imagined, but ... If the rc file is shared/emailed/used outside the config directory, the filename won't have any information to identify the application it belongs to. I'm not at home now, but I bet if I list all _*rc_ files under _~/.config_, their filenames will contain the name of the applications they belong to. I feel it's just a question of being able to identify the file just from looking at its basename.

**Comment by rndusr** [comment]
When I look through `tree ~/.config` I see i3, termit, udiskie, youtube-dl and
qutebrowser that don't have their name in the config filename.

When you share an rc, you can name it anything you like and load it via
`--rcfile` or `rc`. I don't really see the issue.

**Comment by marcelpaulo** [comment]
>  i3, termit, udiskie, youtube-dl, qutebrowser

Indeed, _config_, _rc.lua_, _autoconfig.yml_. It seems we got down to personal taste (By the way, good tips: I'll try out termit, udiskie and qutebrowser)
