### ISSUE TITLE
suppress confirmation

### ISSUE THREAD

**Issue by GodsVictory** [rndusr/stig#73]
How can I confirm deletion of torrents programmatically? Currently, when using:
    
    stig rm -d 'ratio>1'

you are prompted with:

    Are you sure you want to remove 11 torrents? [y|n]

Is it possible to automatically confirm?

**Comment by rndusr** [comment]
I'll add a `--force` option to `rm`.

For now, try setting `remove.max-hits` to a number higher than the amount of
torrents you want to delete, e.g. `stig set remove.max-hits 1M \; rm -d 'ratio>1'`.

**Comment by GodsVictory** [comment]
that worked, thanks!
