### ISSUE TITLE
tui.theme = theme: Invalid attribute name: 'torrentlist.connections.header'

### ISSUE THREAD

**Issue by oblitum** [rndusr/stig#74]
I'm getting the error "tui.theme = theme: Invalid attribute name: 'torrentlist.connections.header'" after the latest update on AUR, I have no idea why. I can't start stig.

**Comment by oblitum** [comment]
Ah... I just had to update my theme.

**Comment by rndusr** [comment]
Yeah, sorry about that. I hope this is the last breaking change I'm going to
make. But probably not.

**Comment by oblitum** [comment]
Yeah, it was not.... 

```
~ ❯❯❯ stig
set: tui.theme = theme: Invalid attribute name: 'peerlist.ip.header'
```

**Comment by rndusr** [comment]
It's called `peerlist.host` now because there's an option to reverse-lookup the IP.

Sorry about that.

**Comment by denis-khizhniak** [comment]
Sorry to bump up this but now there is another one:
`set: tui.theme = custom.theme: Invalid attribute name: 'scrollbar'`

**Comment by rndusr** [comment]
Check out the default theme. Scrollbars are now themed differently depending on
their context.

**Comment by denis-khizhniak** [comment]
@rndusr, thank you, with default it works.
