### ISSUE TITLE
filter by how long torrent has been completed

### ISSUE THREAD

**Issue by GodsVictory** [rndusr/stig#75]
This may already be possible, can we filter based on how long a torrent has been completed?

      Completed: 2018-05-12 09:24 (2d23h ago)
                                      ^^^ This is the part of the field I need

So we could invoke something like this:

    stig rm -d 'completed>8h'
to remove all torrents that have been completed for more than 8 hours.

**Comment by GodsVictory** [comment]
This is what I'm using now:

    stig rm -d "completed<$(date +%H:%M --date="8 hours ago")"

thanks!

**Comment by rndusr** [comment]
Clever! Thanks for sharing.

But I'd use the full date, not just the time, in case you run this before 8:00
in the morning and something weird happens.

**Comment by GodsVictory** [comment]
%F = YYYY-MM-DD
