### ISSUE TITLE
Process title not being updated in tmux

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#78]
Just noticed today that the process title is not being updated in tmux anymore. Not sure from which commit it stopped updating it, I've only noticed today. The process title is correct:

```
paulo:~$ ps -o pid,comm 4271
  PID COMMAND
 4271 stig
```

but it's not updated in tmux:
![image](https://user-images.githubusercontent.com/10074769/40584724-3e8a386e-617c-11e8-9da2-abad1a0edac9.png)

I'm running stig 46cb0a9bbca25b0af7fd2c0533f00b91443f34bc on Xubuntu 18.04, and here's proctitle:

```
paulo:~$ pip3 show setproctitle
Name: setproctitle
Version: 1.1.10
Summary: A Python module to customize the process title
Home-page: https://github.com/dvarrazzo/py-setproctitle
Author: Daniele Varrazzo
Author-email: daniele.varrazzo@gmail.com
License: BSD
Location: /home/paulo/.local/lib/python3.6/site-packages
Requires: 
```

**Comment by rndusr** [comment]
Works fine for me.

Same stig commit, same setproctitle version.
tmux is 2.7.

IIRC, the only thing stig is supposed to do is change the process title.  If
that works, it must be something else.

**Comment by marcelpaulo** [comment]
My sincerest apologies, I overlooked something: I'm now setting the window titles, so tmux doesn't change them dynamically. You're right, stig is correctly changing the process title.
