### ISSUE TITLE
Filters in a list of commands (separated by ;) not executed sequentially from left to right

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#79]
A list of stig commands separated by **;** is not executed sequentially, from left to right. Or to be more precise, **all** filters seem to be evaluated **before** running the commands, and then the commands are executed sequentially from left to right.

To give an example that has just bit me when I tried to set up a maintenance script, consider these torrents:

```
paulo:~/tmp$ stig ls "activity < $(date -d '1 day ago' +'%F %T')"
Size B│Dn  B│Up B│Ratio│Seeds│Peers│Status │ETA│  %│Activity  │Dn b/s│Up b/s│Name                                          
 9.73M│9.73M│   0│    0│    ?│    0│seeding│  ?│100│2018-06-01│     0│     0│Damian Conway - Perl Best Practices - 2005.pdf
  124M│ 124M│   0│    0│    1│    0│seeding│  ?│100│2018-06-01│     0│     0│Francis Hime & Guinga - 2013 Francis e Guinga 
  394M│ 394M│   0│    0│    ?│    0│seeding│  ?│100│2018-06-01│     0│     0│Productivity for Programmers                  
```

I want to stop them and list them with a single list of stig commands, so I tried:

```
paulo:~/tmp$ stig stop "activity < $(date -d '1 day ago' +'%F %T')" \; ls stopped
Found 3 activity<2018-06-01 torrents
Stopping Productivity for Programmers
Stopping Damian Conway - Perl Best Practices - 2005.pdf
Stopping Francis Hime & Guinga - 2013 Francis e Guinga
No matching torrents: stopped
```

After running `stop`, `ls stopped` should have listed the 3 torrents that were stopped. If I run it separately, it works, of course:

```
paulo:~/tmp$ stig ls stopped
Size B│Dn  B│Up B│Ratio│Seeds│Peers│Status │ETA│  %│Activity  │Dn b/s│Up b/s│Name                                          
 9.73M│9.73M│   0│    0│    ?│    0│stopped│   │100│2018-06-01│     0│     0│Damian Conway - Perl Best Practices - 2005.pdf
  124M│ 124M│   0│    0│    2│    0│stopped│   │100│2018-06-01│     0│     0│Francis Hime & Guinga - 2013 Francis e Guinga 
  394M│ 394M│   0│    0│    ?│    0│stopped│   │100│2018-06-01│     0│     0│Productivity for Programmers                  
```

**Comment by rndusr** [comment]
That's because the transmission-daemon API doesn't offer any way to wait for the
stop command to finish. You can say "stop these torrents", but can't say "tell
me when you're done".

As a result, `stig stop ...` returns when the API call was dispatched, not when
the torrents are actually stopped.

The easiest workaround is probably to run stig two times:

    stig stop ... ; stig ls stopped

stig's startup should be slow enough for Transmission to stop the torrents
before the `ls` command is executed.  But there is no guarantee.

**Comment by marcelpaulo** [comment]
> That's because the transmission-daemon API doesn't offer any way to wait for the stop command to finish

Oh, it did occur to me, I could and should have checked this before opening the issue. My bad.

Thanks for your patience with my unnecessary issues !

**Comment by rndusr** [comment]
No worries. I agree that it's unintuitive.
