### ISSUE TITLE
Filter 'foo & !bar' or 'foo | !bar' fail parsing: Malformed filter expression

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#81]
I've been fidgeting with my torrent cleanup script, and bumped into a parsing problem. A filter with **&** or **|** followed by **!** is not parsed correctly. An example:

```
paulo:~/tmp$ st ls 'foo & !bar'
Malformed filter expression: ' !bar'
```

whereas this parses correctly:
```
paulo:~/tmp$ st ls '!foo & bar'
No matching torrents: !~foo&~bar
```

but the semantics is different, since it seems that **&** has precedence over **!**, as if the expression were **!(foo & bar)**.

I can work around this, but I thought I should let you know.

**Comment by rndusr** [comment]
Removing the spaces seems to work?: `foo&!bar`

But it should obviously also work with spaces.

**Comment by marcelpaulo** [comment]
Shame on me, it didn't occur to me to remove the spaces ! I noticed that stig removes the spaces after it parses the filters, for instance:

```
paulo:~/tmp$ stig ls 'complete & activity < 2018-06-13'
No matching torrents: complete&activity<2018-06-13
```

so I thought it was just the same with or wihout spaces. But you're right, without the spaces, those filters are parsed correctly.

**Comment by rndusr** [comment]
No shame on you! It *should* behave identical with or without the spaces.
This is a bug.

I would actually prefer to preserve the spaces when printing a filter, but the
parser is quite complex and messy as it is.

**Comment by marcelpaulo** [comment]
Working fine now, thanks !
