### ISSUE TITLE
Tab completion when moving torrents

### ISSUE THREAD

**Issue by Erebea** [rndusr/stig#85]
This is about the only thing keeping me from switching from tremc. I find tab-completion when changing output directories to be an essential feature of TUI torrent clients.

cheers

**Comment by rndusr** [comment]
Yup, that'd be great.

But how does it work if transmission-daemon runs on a remote server?

**Comment by Erebea** [comment]
It probably doesn't. I don't know how tremc handles it as I don't run a remote transmission-daemon; it might just disable it. A possible way to do it would be making use of a network mount and translating that path to work with the filesystem of the remote server.

**Comment by rndusr** [comment]
Maybe. Or there could be a configurable command (ssh) that returns the directory
tree on the server.

Anyway, it will probably be a while before I get to implementing a completion
system. Don't wait for it.

**Comment by rndusr** [comment]
@Erebea This is not a substitution for completion in the built-in CLI, but I
just had an idea.

If you move your torrents to a small-ish set of directories, you could add some
chained keybindings like this:

    bind --context torrent 'm a' move archive
    bind --context torrent 'm o v' move 'old/very old'
    bind --context torrent 'm o n' move 'old/not so old'

That would allow you to focus one torrent or even select a few with space and
then hit `m` and then `a` to move them to the `archive` directory, which would
be faster than any completion system. But you'd also be limited to a fixed set
of directories.

**Comment by rndusr** [comment]
@Erebea Tab completion isn't finished overall, but it's been working well for me with the development version. Master branch is currently not a hot mess, so if you're still waiting, you may want to try the development version now.

**Comment by Erebea** [comment]
Tried the development version with `pip3 install --upgrade git+https://github.com/rndusr/stig.git#egg=stig` but I'm getting this whenever I try a command.

> Traceback (most recent call last):
>   File "/home/erebea/.local/bin/stig", line 11, in <module>
>     sys.exit(run())
>   File "/usr/local/lib/python3.6/dist-packages/stig/__init__.py", line 24, in run
>     main.run()
>   File "/usr/local/lib/python3.6/dist-packages/stig/main.py", line 115, in run
>     if not tui.run(run_commands):
>   File "/usr/local/lib/python3.6/dist-packages/stig/tui/main.py", line 206, in run
>     urwidloop.run()
>   File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 286, in run
>     self._run()
>   File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 384, in _run
>     self.event_loop.run()
>   File "/usr/local/lib/python3.6/dist-packages/stig/tui/urwidpatches.py", line 175, in run
>     raise self._exc_info
>   File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/usr/local/lib/python3.6/dist-packages/stig/tui/cli.py", line 207, in callback
>     task.result()
>   File "/usr/local/lib/python3.6/dist-packages/stig/tui/completer.py", line 100, in update
>     cands.reduce(r'(?i)^%s' % (re.escape(common_prefix),))
>   File "/usr/local/lib/python3.6/dist-packages/stig/completion/__init__.py", line 170, in reduce
>     if not isinstance(regex, re.Pattern):
> AttributeError: module 're' has no attribute 'Pattern'

**Comment by rndusr** [comment]
Thanks for reporting that.
Should be fixed now.

**Comment by Erebea** [comment]
Everything seems to be working fine!

**Comment by BachoSeven** [comment]
What is the current state of this?

**Comment by Erebea** [comment]
Been using it ever since, works on my machine.

**Comment by BachoSeven** [comment]
Is it only on the development version?

**Comment by rndusr** [comment]
I've been using it for months without issues.

I guess I forgot to close this. Unless I forgot the reason it's still open.

**Comment by BachoSeven** [comment]
It does not work for me on the latest release, installed using pipx.

**Comment by rndusr** [comment]
> Is it only on the development version?

Yes.
