### ISSUE TITLE
search command on peer list results in "Invalid filter name" for any filter

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#87]
`search` on a peer list results in `Invalid filter name` for any filter. I wasn't sure which field the search term would apply to, I tried characters present in `client`, `country` and `ip`, but all searches resulted in `Invalid filter name`. For instance, given this peer list:
![image](https://user-images.githubusercontent.com/10074769/42535641-4ad1de4e-8466-11e8-9182-36f54d81492a.png)

I search for letters ***o***, ***e*** and digit ***3***, and they all resulted in `Invalid filter name`:
![image](https://user-images.githubusercontent.com/10074769/42535754-a769efac-8466-11e8-90b2-fd08fdfb6bbf.png)

Running latest master (39f30e6485c39342e3e2327b7eab4ff6506ba7d0) on Xubuntu 18.04

**Comment by rndusr** [comment]
The peer list doesn't have a default filter. I should probably set one, but I'm
not sure which one. Maybe the host name?

Searching for `client~deluge`, for example, works fine for me. It's just
spamming out error messages because `c`, `cl`, `cli`, etc are all not valid
filter names. It stops when I reach `client~d`, because that's valid. I'll have
to rewrite how error messages are created, which will take a while.

**Comment by marcelpaulo** [comment]
Oh, I see, some lists have a default filter. I see now it's `name` for torrent and file list. but tracker and peer lists have no default filter. I'd choose definitely `domain` for tracker list, and perhaps `ip` for peer list.

Searching against a field works fine, you're right.

Really useful feature, `search`, congratulations !

**Comment by rndusr** [comment]
Tracker lists should already use `domain` as the default filter.

And I thought `domain~o` still didn't show any results?

**Comment by marcelpaulo** [comment]
The peer list filters are behaving strange: they work with `search` but not as an `lsp` filter:

```
paulo:~/src/stig (master)$ stig lsp name~sharp
IP                                     │Client            │Country│   %│Dn b/s│Up b/s│Est b/s│ETA│Torrent
                          46.166.191.13│qBittorrent 4.1.1 │     NL│   0│     0│     0│      0│  ?│Sharp.Objects.S01E01.WEB.H264-DEFLATE[ettv]
   catv-80-98-122-159.catv.broadband.hu│BitTorrent 7.0.3  │     HU│   0│     0│     0│      0│  ?│Sharp.Objects.S01E01.WEB.H264-DEFLATE[ettv]
           ti0205a430-0282.bb.online.no│µTorrent Mac 1.8.7│     NO│   0│     0│     0│      0│  ?│Sharp.Objects.S01E01.WEB.H264-DEFLATE[ettv]
177.133.223.186.dynamic.adsl.gvt.net.br│Deluge 1.3.15.0   │     BR│24.7│     0│     0│      0│  ?│Sharp.Objects.S01E01.WEB.H264-DEFLATE[ettv]
paulo:~/src/stig (master)$ stig lsp 'name~sharp & client~deluge'
Invalid filter name: 'client'
```

**Comment by rndusr** [comment]
You made the same mistake as earlier: `lsp` takes two arguments. The first is a
torrent filter, the second is a peer filter.

**Comment by marcelpaulo** [comment]
I was just about to come here and confess my mistake, but you got here first ! My sincerest apologies !

**Comment by rndusr** [comment]
No biggie. Everyone makes mistakes.
