### ISSUE TITLE
Filter based on location

### ISSUE THREAD

**Issue by GodsVictory** [rndusr/stig#88]
Might already be possible. I'd like to be able to filter based on data location.

**Comment by rndusr** [comment]
stig help filter | grep path
    stig ls 'path~any/part/of/an/interesting/path'
    stig ls 'path=/absolute/path/to/the/torrent/i/want'

**Comment by GodsVictory** [comment]
perfect, thanks!

Is it possible to group filters? For instance, path~something&(ratio>1|completed>2)

**Comment by rndusr** [comment]
Please read the documentation before asking questions.

```
stig help filter | less
```

**Comment by rndusr** [comment]
Oh, I see. Sorry.

No, grouping is not possible at the moment.
