### ISSUE TITLE
Typo in `default.theme`

### ISSUE THREAD

**Issue by kazuoteramoto** [rndusr/stig#9]
In `stig/settings/default.theme` the foreground colors use `$list_bg` instead of `$name.stopped_fg`
```diff
index a354f08..bd97431 100644
--- i/stig/settings/default.theme
+++ w/stig/settings/default.theme
@@ -180,12 +180,12 @@ torrentlist.name.queued.complete.unfocused         $name.queued_fg           on
 torrentlist.name.queued.complete.focused           $name.queued_fg           on $list_bg.f

 $name.stopped_fg = dark gray
-torrentlist.name.stopped.progress1.unfocused       $list_bg.f,underline  on $list_bg.uf
-torrentlist.name.stopped.progress1.focused         $list_bg.uf,underline on $list_bg.f
-torrentlist.name.stopped.progress2.unfocused       $list_bg.f            on $list_bg.uf
-torrentlist.name.stopped.progress2.focused         $list_bg.uf           on $list_bg.f
-torrentlist.name.stopped.complete.unfocused        $list_bg.f            on $list_bg.uf
-torrentlist.name.stopped.complete.focused          $list_bg.uf           on $list_bg.f
+torrentlist.name.stopped.progress1.unfocused       $name.stopped_fg,underline on $list_bg.uf
+torrentlist.name.stopped.progress1.focused         $name.stopped_fg,underline on $list_bg.f
+torrentlist.name.stopped.progress2.unfocused       $name.stopped_fg           on $list_bg.uf
+torrentlist.name.stopped.progress2.focused         $name.stopped_fg           on $list_bg.f
+torrentlist.name.stopped.complete.unfocused        $name.stopped_fg           on $list_bg.uf
+torrentlist.name.stopped.complete.focused          $name.stopped_fg           on $list_bg.f

 $name.verifying_fg = yellow
 torrentlist.name.verifying.progress1.unfocused     $name.verifying_fg,underline on $list_bg.uf
```

**Comment by upodroid** [comment]
I applied the changes an made a PR :)

**Comment by kazuoteramoto** [comment]
@rndusr Do you prefer trivial/small patches like this a issues or pr?

**Comment by upodroid** [comment]
I'm new to this so I'm fine with small patches.

**Comment by rndusr** [comment]
@kazuoteramoto I don't have any preferences for now.

But your patch breaks the display of stopped torrent names. And the only
problem I see is that `$name.stopped_fg` is useless.

**Comment by kazuoteramoto** [comment]
That was not a patch. I don't use the default theme, because it is broken with my colorscheme (gruvbox). But when I was changing it I noticied that this part was not using the correct variables.

The problem is that both `$name.stopped_fg` and `$list_bg.f` and are both `dark gray` so its is have the same color when a stopped torrent is focused.

I don't think `$name.stopped_fg` is useless, the problem is using the same color was background and foreground. But as I said the default theme looks bad in my colorscheme so I can't comment on what colors to use.

**Comment by kazuoteramoto** [comment]
Wait, I think I understand you used $list_bg so that it is the inverse of the focused stopped to avoid the problem above right? ok I understand now, my mistake. I just that when changing the theme is strange the list_bg (background) changed foreground colors and name.stopped_fg (foreground) did not.

Closing.

**Comment by rndusr** [comment]
Yes, stopped torrents use the same colors as the list background (focused/unfocused).

I agree that this is confusing. The whole theme design isn't very pretty. The
problem is that urwid's palette system is very simple and stig has very
complex decorations.

I'm open to suggestions.

**Comment by kazuoteramoto** [comment]
I think the biggest problem is that is nearly impossible to find a single background color that works with most of the foreground colors, I my case most foreground colors looks horrible over dark gray.

What I did was to remove all the background colors (set then to black) and use bold to mark focused, but not everyone like bold on terminal.

Another option is to not used foreground and use standout for focused because its automatic adapts to the foreground. I tried this first and looks ok-ish, the problem is that we have some spaces on the columns that look ugly (not that they also appears on the header underline).
![2017-01-29-120805_1366x768_scrot](https://cloud.githubusercontent.com/assets/291287/22404622/e829ba94-e61b-11e6-9442-b530095a02da.png)

**Comment by rndusr** [comment]
Yeah, I don't think it's possible to create a theme that is even readable with
all color schemes. At least not with that much complexity.

The best way would probably be to include a bunch of different themes that
users can select easily. I haven't put any work into that because the default
theme is ugly and I was hoping to come up with something better, and also
because it's going to change quite a bit with more TUI elements being added.

A 256-color theme would solve that issue at least for terminals that support
it, but it always takes me days of fiddling to figure out good-looking color
combinations, so I haven't made one yet.
