### ISSUE TITLE
move behaves differently if destination path ends on /

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#91]
I can explain this more quickly with a concrete example:

Given this torrent:

```
paulo:~/tmp$ stig ls -c name,path preacher
Name                                │Path
Preacher.S03E04.HDTV.x264-SVA[rarbg]│/home/paulo/Downloads/done
```

if the destination path **doesn't end on /**, `stig mv` to _~/Downloads/done_ correctly reports that the torrent is already there:

```
paulo:~/tmp$ stig mv 'name=Preacher.S03E04.HDTV.x264-SVA[rarbg]' ~/Downloads/done
move: Found 1 =Preacher.S03E04.HDTV.x264-SVA[rarbg] torrent
move: Already in /home/paulo/Downloads/done: Preacher.S03E04.HDTV.x264-SVA[rarbg]
```

but if the destination path **ends on /**, stig reports that it's moving the torrent:

```
paulo:~/tmp$ stig mv 'name=Preacher.S03E04.HDTV.x264-SVA[rarbg]' ~/Downloads/done/
move: Found 1 =Preacher.S03E04.HDTV.x264-SVA[rarbg] torrent
move: Moving to /home/paulo/Downloads/done/: Preacher.S03E04.HDTV.x264-SVA[rarbg]
```

As you've prefixed stig's messages with the command being run, I had to amend a script that parsed stig's output, and when I tested it, I bumped into this issue.

**Comment by rndusr** [comment]
I thought I had already fixed that.

Hopefully it's fixed now.

**Comment by marcelpaulo** [comment]
Indeed, 817c97b fixed it ! Thanks !
