### ISSUE TITLE
[question] How to run the tests ?

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#92]
I've just seen that you committed a lot of changes to the tests, so I wondered how to run them. I tried:

```
paulo:~/src/stig (master)$ python3 setup.py test
/usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '0.9.0a' to '0.9.0a0'
  normalized_version,
running test
Searching for asynctest>=0.11
Reading https://pypi.python.org/simple/asynctest/
Downloading https://files.pythonhosted.org/packages/ee/29/9a9289a11b56ceb28dc18fc5b1af9b4223a387269252bb0f349c9da2ed10/asynctest-0.12.2-py3-none-any.whl#sha256=56bd75b03df55956d57437db26700503d1013616314db5d1ea1a73be1186fd71
Best match: asynctest 0.12.2
Processing asynctest-0.12.2-py3-none-any.whl
Installing asynctest-0.12.2-py3-none-any.whl to /home/paulo/src/stig/.eggs

Installed /home/paulo/src/stig/.eggs/asynctest-0.12.2-py3.6.egg
running egg_info
writing stig.egg-info/PKG-INFO
writing dependency_links to stig.egg-info/dependency_links.txt
writing entry points to stig.egg-info/entry_points.txt
writing requirements to stig.egg-info/requires.txt
writing top-level names to stig.egg-info/top_level.txt
reading manifest file 'stig.egg-info/SOURCES.txt'
writing manifest file 'stig.egg-info/SOURCES.txt'
running build_ext
Unknown command: test
```

but had no success. Please forgive my Python ignorance !

**Comment by marcelpaulo** [comment]
Forgot to add: I'm running latest master (f74e691).

**Comment by rndusr** [comment]
> ```
> Unknown command: test
> ```

That's the output of `stig test`. No idea why that happens. If I run the same
command, I get a totally different error that I also can't explain. I've never
had much luck with Python's built-in test runner, so I'm probably not going to
fix that.

I use [pytest](https://docs.pytest.org/en/latest/) as a test runner, which is
probably packaged by your distro, and it should work like this when you're in
the project directory: `python3 -m pytest ./tests`

I run my tests in a virtual environment, which you can setup with `make venv`,
activate it with `source ./venv/bin/activate` and run the tests with `make
tests`.

**Comment by marcelpaulo** [comment]
Thanks for the explanation !

I haven't got there yet :-( Installed package `python3-pytest` and ran:

```
python3 -m pytest ./tests
```

but got repeated errors:

```
    import asynctest
E   ModuleNotFoundError: No module named 'asynctest'
```

Looked for the module in the project directory:

```
paulo:~/src/stig (master)$ find . -name '*asynctest*'
paulo:~/src/stig (master)$
```

Looked for it in the distribution:

```
paulo:~/src/stig (master)$ apt-file search asynctest
python-twisted-core: /usr/lib/python2.7/dist-packages/twisted/trial/_asynctest.py
python3-twisted: /usr/lib/python3/dist-packages/twisted/trial/_asynctest.py
```

Installed package `python3-twisted`, and repeated the tests, but got the same errors :-(

**Comment by rndusr** [comment]
Sorry, I forgot about asynctest. It's a library that helps with testing
asynchronous code. If it's not packaged by your distro, you can install it from
pypi.org with `pip3 install asynctest` (installs to /usr/local) or `pip3 install
--user asynctest` (installs to ~/.local).

Or you can go the virtual environment route. `make venv` installs asynctest
automatically for you in the virtual env, and you can undo everything with a
simple `rm -rf venv`.

**Comment by marcelpaulo** [comment]
> If it's not packaged by your distro, you can install it from pypi.org

I could and should have remembered pypi :-(

Tests ran OK now !

> you can go the virtual environment route

I did go, but it spit some errors. I didn't want to get sidetracked, nor bother you with still more basic Python stuff unrelated to stig, so I didn't pursue it further. But I will now.

Using stig and interacting with you has been teaching me quite some Python, thanks for that, for stig and for your patience !

**Comment by rndusr** [comment]
Glad to help. I'd be happy to be available for more unrelated-to-stig-but-
python-in-general questions, but I don't want to post my email here publicly and
github doesn't have private messages anymore. If you can think of anything, I'm
all ears.

Anyway, running the tests is definitely related to stig. There should actually
be a section in the readme that explains how to do that, so I'd be interested in
your error messages.

**Comment by marcelpaulo** [comment]
> I'd be happy to be available for more unrelated-to-stig-but-python-in-general questions […] If you can think of anything, I'm all ears

Thanks for the kind offer :-) Off the top of my head, can't think of a way, but will sure look for one !

> running the tests is definitely related to stig

I saw now that _README.org_ does already list `asynctest` as a requirement for tests, I couldn't have seen it before :-(

> I'd be interested in your error messages

Ran `make venv &> >(tee venv.log)`, this error message is repeated:

```
  error: invalid command 'bdist_wheel'
```

Here's full [venv.log](https://paste.ee/p/5ujmr).

I hadn't noticed there was a _Makefile_ !

**Comment by rndusr** [comment]
I think you can ignore that bdist_wheel error. It says later in your log that
all those packages where installed successfully.

But I've added wheel to the packages that are installed in the virtual env. That
should fix the ugly error message.

**Comment by marcelpaulo** [comment]
> I think you can ignore that bdist_wheel error. It says later in your log that all those packages where installed successfully.

To be honest, I hadn't looked attentively at the log, and you're right, even though it contains:

```
Failed to build blinker urwidtrees idna-ssl
```

right after that message:

```
  Running setup.py install for idna-ssl: started
    Running setup.py install for idna-ssl: finished with status 'done'
  Running setup.py install for blinker: started
    Running setup.py install for blinker: finished with status 'done'
  Running setup.py install for urwidtrees: started
    Running setup.py install for urwidtrees: finished with status 'done'
```

> But I've added wheel to the packages that are installed in the virtual env. That should fix the ugly error message.

Indeed it has ! Whole test procedure well oiled, with no error messages:

```
make venv
source ./venv/bin/activate
make test
```

Looking at _./venv/bin/activate_, I see that `deactivate` gets me out of the virtual environment.

**PS:** Sorry for the delay, github still hasn't sent me the notification email of your last post.

**Comment by rndusr** [comment]
Glad it's working now.

And don't worry about delays. This isn't a chat were I'm actively waiting for replies.
