### ISSUE TITLE
Implement comment as a torrent comparative filter

### ISSUE THREAD

**Issue by marcelpaulo** [rndusr/stig#94]
Would it be feasible to implement `comment` as a torrent comparative filter ?

I caught myself needing to filter torrents that had a particular comment, and then realized that `comment` is not a comparative filter.

**Comment by rndusr** [comment]
Yup, that's trivial.

It should work as expected in the latest commit.

**Comment by marcelpaulo** [comment]
Oh, this really simplify my workflow, you wouldn't know ! Thank you so much, I've just took it for a spin, it's humming along nicely !
