### ISSUE TITLE
Have to revert to `transmission-remote` for magnet link.

### ISSUE THREAD

**Issue by DiagonalArg** [rndusr/stig#97]
`transmission-remote -t <n> -i` returns the magnet link for the torrent, while `stig info <name>` only returns the hash.  Would you consider adding the link?  It would make it a lot easier to share torrents with others.

Also, I'll point out that I was not able to find in the help pages any info on specifying the torrent in the `stig info` command.  I found it by playing around, but assuming I haven't overlooked it, perhaps you want to specify that.

Fantastic software, by the way.  I almost get chills when I use it.  :)c

**Comment by rndusr** [comment]
Adding the magnet link is a good idea. Thanks.
I've added it to my todo list.


I'm sorry the documentation failed you.

Did you discover `stig help info`? It says that the command takes a single
argument which is described as "Torrent filter expression (see TORRENT FILTERS
section in `help filter`) or focused torrent in the TUI if omitted".

I don't know how to make it any clearer. Do have a suggestion?


> Fantastic software, by the way.  I almost get chills when I use it.  :)c

What a nice compliment. Thank you!
Maybe I should open a fan shop and sell sex toys. :)

**Comment by rndusr** [comment]
Oh, I see. I guess I thought that's just common sense. (Settings are also help
topics, in case you didn't know.)

I'll try to make that clear. Probably in the main help (`stig help`).

Thanks for your feedback.

**Comment by rndusr** [comment]
I've included more information in the `stig help` output and added a `magnet`
command that simply prints magnet URIs for the specified torrents.

I considered including the magnet in the `info` output, but they can be really
long and mess everything up, especially with lots of trackers.

**Comment by DiagonalArg** [comment]
Fantastic!

Oh, and by the way, I mentioned you here:
https://github.com/majestrate/XD/issues/2#issuecomment-302540648

That guy's making a bittorrent client for I2P.

**Comment by rndusr** [comment]
I wish I knew about this back in February. I'm not a big fan of the Transmission
RPC and stig should be able to support almost any other protocol. But I guess
that's water under the bridge now.

Interesting project anyway. Thanks for sharing.

**Comment by DiagonalArg** [comment]
Ah, well that was my ignorance.  Why don't you let him know?  He may not have made much progress.  I'm sure he'd be happy to hear from someone with experience.

**Comment by rndusr** [comment]
It's been half a year and the readme now says "soon". That sounds like he's
already working on it. And he said he knows Transmission RPC, so he probably
already knows about its issues.

There are also advantages to using it, mainly that you can use any Transmission
client to control XD.
